### ISSUE TITLE
HistorialRecords() doesn't seem to work on Abstract models

### ISSUE THREAD

**Issue by eduvik** [treyhunner/django-simple-history#143]
I have an abstract model, and have attempted to put add HistoricalRecords() to it, but any classes based on this do not get given historical records.

**Comment by Silox** [comment]
Would love this feature too

**Comment by rocktavious** [comment]
This feature was added in #112 and its working great, i use it in a project for work on numerous models and haven't had any issues with it!
I think this issue can be closed

**Comment by macro1** [comment]
Agree, as the feature has been released this is resolved. As noted in #224, in some cases it's possible to have table names that reflect an incorrect app, but that is a bug that will be addressed there.
