### ISSUE TITLE
Django 1.8: ImportError: No module named related

### ISSUE THREAD

**Issue by KevinGrahamFoster** [treyhunner/django-simple-history#156]
```
  File "/Users/thekgf/CentriFile/allay/venv/lib/python2.7/site-packages/simple_history/models.py", line 13, in <module>
    from django.db.models.related import RelatedObject
ImportError: No module named related
```

Django 1.8 has made some changes here and removed the RelatedObject API. More details are here: https://docs.djangoproject.com/en/dev/releases/1.8/#model-attribute-on-private-model-relations

**Comment by macro1** [comment]
Yeah. I've looked a little at it, but I haven't figured out what the solution is yet. If anyone else would like to try, please feel free! @treyhunner and I will both be at PyCon in Montreal in April as well. We talked a little about doing some sprints while we're there if this isn't fixed by then.

**Comment by KevinGrahamFoster** [comment]
Hey guys, I was wondering if this change is appropriate to fix it, and if not, what the issue is with it? I see some warnings that it degraded the quality of the build, but can't find what it degraded.

https://github.com/treyhunner/django-simple-history/pull/157

**Comment by macro1** [comment]
I know the comments are mostly from Landscape, but it's only testing code
style. It's breaking all of the builds in travis:
https://travis-ci.org/treyhunner/django-simple-history/builds/53095209

Unless those all pass we can't merge it.

**Comment by phoebebright** [comment]
FYI - I fixed another app for this with these steps:
In the imports section
    -from django.db.models.related import RelatedObject
   +
   +try:
   +	from django.db.models.related import RelatedObject as ForeignObjectRel
   +except:
   +	# django 1.8 +
   +	from django.db.models.fields.related import ForeignObjectRel
   +	
the replace all RelatedObject with ForeignObjectRel

**Comment by macro1** [comment]
Thanks Phoebe... Our situation was a little more complex, but it looks like
we will able to remove use of related completely (#160).

**Comment by phoebebright** [comment]
Good!

**Comment by RafaelOrtiz** [comment]
Looking forward to have this packaged, this incompatibility is preventing our migration to 1.8, we are using simple-history as a third party app.

**Comment by mhulse** [comment]
+1, looking forward to an update. Thanks for the awesome module. :+1: :octocat:
