### ISSUE TITLE
Information about user is lost when user is deleted

### ISSUE THREAD

**Issue by totycro** [treyhunner/django-simple-history#158]
Hi,

I noticed that when you delete a user, history_user_id is set to NULL for all actions of the user. In my case, this is quite bad.

This could easily be fixed by changing this field to an IntegerField (as far as I know, there is no setting in Django to allow invalid keys if ForeignKeyField is used).

regards,
totycro

**Comment by macro1** [comment]
What you're asking for isn't possible if you're using FK's correctly. Relational databases don't have a concept of latent relationships. Either there is a related record, as indicated by the foreign key, or there isn't, and we chose to allow that by setting the field to 'NULL'. Previously we allowed the delete to cascade and remove the historical record.

Django actually recognizes the issues that arrise from deleting users, and [provides a way to disable users](https://docs.djangoproject.com/en/1.8/ref/contrib/auth/#django.contrib.auth.models.User.is_active) without deleting them and destroying the record relationships.

**Comment by mauricioabreu** [comment]
I agree with @macro1 

This is why Django has a is_active field on User model. 

Can you give some feedback about this so this issue can be closed? Thanks!

**Comment by totycro** [comment]
Well I would still prefer to have the user id saved as integer, possibly in addition to actual foreign key. But I do see that this isn't an ideal solution, so I guess you're free to consider this a "won't fix".

**Comment by macro1** [comment]
Thanks for getting back to us @totycro. Closing.
