### ISSUE TITLE
One-to-one relations can cause models.DoesNotExist Error

### ISSUE THREAD

**Issue by bradford281** [treyhunner/django-simple-history#162]
If an object is created with a one-to-one relation, opportunity for breaking the History admin exists. 
To replicate:

1. Create an object to be related (RelatedA)
2. Create a SimpleHistory enabled object relating to it (ObjectB->RelatedA)
3. Create another object to be related (RelatedC)
4. Update the relation (ObjectB->RelatedC)
5. Delete the original related object (RelatedA.delete())
6. Go to "History" for ObjectB

Raises models.DoesNotExist

**Comment by ryangallen** [comment]
More so, deleting a related object stored as a former related field object breaks the objects history.

For instance, if history is tracked on an Employee model, changing an employee's manager and then deleting the former manager object causes this error when trying to access the employee's history.
