### ISSUE TITLE
Exclude fields?

### ISSUE THREAD

**Issue by jmfederico** [treyhunner/django-simple-history#165]
Hello

I have a usage case where I need to keep a field on a model which I don't want to have versioned. How can I exclude a field from the simple_history model?

Thanks in advance for you help.

**Comment by macro1** [comment]
If anyone (@luzfcb?) wants to take a stab at this (and possibly also add support for both a 'included fields' and 'excluded fields' list) the code that populates new historical records is in [`create_historical_record()`](https://github.com/treyhunner/django-simple-history/blob/1.6.3/simple_history/models.py#L237), and the code that defines historical models from the original model is in [`HistoricalRecords.copy_fields()`](https://github.com/treyhunner/django-simple-history/blob/1.6.3/simple_history/models.py#L125).

I'm not entirely sure how recreating the original model would work, with only part of the data recorded though. Maybe just raise an error if only part of the model's data is being tracked. That code can be found in [`get_instance()`](https://github.com/treyhunner/django-simple-history/blob/1.6.3/simple_history/models.py#L188).

**Comment by howardjones** [comment]
Is there any movement on this? I'm just looking at simple history now, and I can see it may be a problem for my app - I have some fields that are essentially a cached calculated field. They 'change' as a result of changes in other inputs, but the change isn't interesting from a rollback/audit point of view, and the value can easily be recalculated. 

I might take a crack at it if it's not already in progress.

**Comment by macro1** [comment]
I don't believe anyone is working on this issue right now @howardjones, anything you could contribute would be welcome.

**Comment by howardjones** [comment]
I've been looking at this a bit more today, and there are two separate parts to this:
1) Don't copy fields in a list of excluded fields to the historical copy
2) Don't record a change if the only changed fields are excluded

It's the second one that I really care about personally. I have a few things where I use auto_now DateTimeFields just so the UI can show when an item has changed, but the actual change is in a child item (e.g. line item in an order) so there is no data change in the object other than the last_change field. Updating a child makes the child tell its parent that things have changed, and I get a little cascade of history records, even though only one is a "real" change. I just opened #214 for part of that, but this is what I meant by excluding fields.

Is that in line with other folks' use-case?

**Comment by mgallagher** [comment]
+1

Something like this would be very nice. We have a few `auto_now` fields that don't really need to be tracked.

**Comment by joaojunior** [comment]
I will do this now.

**Comment by joaojunior** [comment]
I did this in PR: https://github.com/treyhunner/django-simple-history/pull/238

**Comment by rlucioni** [comment]
We're using django-extensions' `AutoSlugField` in conjunction with `HistoricalRecords` on some of our models. `AutoSlugField` attempts to create new slugs on create, which includes those historical rows. We would love to see this land!

**Comment by adibo** [comment]
I came along a similar need as described by @howardjones (case 2), and since I have not yet seen this feature request implemented, here is a solution/workaround one could adopt. 
The code is meant to allow for specifying explicitly the fields, the change of which should cause a history of the model being saved (note: all fields are still being saved!).

In short, the idea is:
1) use a decorator for model classes which enables tracking fields' changes (using `pre_save` signal of a given model). The decorator issues its own signal once done.  
2) connect a custom-made signal receiver to the decorator's signal to mark if `django-simple-history` should store this particular change or not (we would use `skip_history_when_saving`)

Here is the code:

ad 1) Here is a e.g. `decorators.py` file
```
from django.db.models.signals import pre_save
from django.dispatch import Signal

## signal sent whenever a data tracking is performed
track_data_performed = Signal(providing_args=["instance"])


def track_data(*fields):
    """
    Based on David Cramer's  track_data.py
    See: http://cramer.io/2010/12/06/tracking-changes-to-fields-in-django

    Here we just add a single line to issue the track_data specific
    signal.
    """

    UNSAVED = dict()

    def _store(self, data=None):
        "Updates a local copy of attributes values"
        if self.id:
            if data:
                self.__data = {f: getattr(data, f) for f in fields}
            else:
                self.__data = {f: getattr(self, f) for f in fields}
        else:
            self.__data = UNSAVED

    def inner(cls):
        # contains a local copy of the previous values of attributes
        cls.__data = {}

        def has_changed(self, field):
            "Returns 'True' if 'field' has changed since initialization."
            if self.__data is UNSAVED:
                return False
            return self.__data.get(field) != getattr(self, field)
        cls.has_changed = has_changed

        def old_value(self, field):
            "Returns the previous value of 'field'"
            return self.__data.get(field)
        cls.old_value = old_value

        def whats_changed(self):
            "Returns a list of changed attributes."
            changed = {}
            if self.__data is UNSAVED:
                return changed
            for k, v in self.__data.iteritems():
                value = getattr(self, k)
                if v != value:
                    changed[k] = value
            return changed
        cls.whats_changed = whats_changed

        # Ensure we are updating local attributes on model pre_save
        def _pre_save(sender, instance, **kwargs):
            if not kwargs.get('raw', False):
                inst = None
                if instance.id:
                    # get old values
                    try:
                        inst = sender.objects.get(id=instance.id)
                    except sender.DoesNotExist:
                        pass
                _store(instance, inst)

                # we emit a unique signal so that others can connect to
                track_data_performed.send(sender=cls, instance=instance)
        pre_save.connect(_pre_save, sender=cls, weak=False)

        # Ensure we are updating local attributes on model save
        def save(self, *args, **kwargs):
            save._original(self, *args, **kwargs)
            _store(self)
        save._original = cls.save
        cls.save = save
        return cls
    return inner
```

ad 2) Here is how to use it in your `models.py` for a model you wish to be track'ed by `django-simple-history`
```
from django.db import models
from simple_history import register as history_register
from decorators import track_data, track_data_performed


@track_data('field_1', 'field_2')
class MyModel(models.Model):
    field_1 = models.CharField(max_length=128)
    field_2 = models.CharField(max_length=128)
    field_3 = models.CharField(max_length=128)
history_register(MyModel, inherit=True)    


@receiver(track_data_performed, sender=MyModel)
def user_save_history(sender, instance, **kwargs):
    if not instance.whats_changed():
        instance.skip_history_when_saving = True

```

Note that only the change of any of the indicated fields will trigger historical object of MyModel to be saved. So if nothing but a `field_3` is changed, no history will be stored.

I hope some of you find it useful. Enjoy!
(tested with Django 1.8 and django-simple-history version 1.8.1).

**Comment by rossmechanic** [comment]
This was fixed in #274 . Releases >=1.9.0 should have an excluded fields option.

**Comment by dwasyl** [comment]
> I've been looking at this a bit more today, and there are two separate parts to this:
>
>1. Don't copy fields in a list of excluded fields to the historical copy
>2. Don't record a change if the only changed fields are excluded
>
>It's the second one that I really care about personally. I have a few things where I use auto_now >DateTimeFields just so the UI can show when an item has changed, but the actual change is in a child >item (e.g. line item in an order) so there is no data change in the object other than the last_change >field. Updating a child makes the child tell its parent that things have changed, and I get a little cascade >of history records, even though only one is a "real" change. I just opened #214 for part of that, but this >is what I meant by excluding fields.

Sorry to dredge up an old issue, but going back to @howardjones's message further back, it seems that the `excluded_fields` function is the first solution. I'm wondering @rossmechanic if the second is possible?

Basically, I have a number of status fields (i.e. modified_on) that I don't mind being saved on the historical version, but when no other fields are updated I don't want a change to that field to trigger saving a historical version. I couldn't figure out a way to have it essentially ignore those fields - but still store them in the history when it does save a historical record.

**Comment by adibo** [comment]
I haven't found an existing solution within `django-simple-history`. 
But you may check my [comment](https://github.com/treyhunner/django-simple-history/issues/165#issuecomment-264847982) above. It is exactly a working solution for problem 2 (i.e. don't record a history if the only changed fields are those who are not relevant to be traced). Looks to me that this should fits your needs too.
(Obviously there is a cost involved of querying db to see whats changed).
