### ISSUE TITLE
IntegrityError: Using Historical Records on an object that inherits from another non abstract object

### ISSUE THREAD

**Issue by KevinGrahamFoster** [treyhunner/django-simple-history#166]
This is just as of the latest version. I cannot edit any objects that inherit from another object.
If I create two objects as so:

```
class Zork(models.Model):
    data = models.IntegerField(blank=True, null=True, default=0)


class Bork(Zork):
    different_data = models.IntegerField(blank=True, null=True, default=0)
    history = HistoricalRecords()
```

Steps to repro:

1. Create an object of type Bork (this creates the object as well as a simplehistory record for bork)
2. Try to edit the object (this will try to create another historical record but will fail with an integrity error)

Reason is the historical record object has a OneToOne relationship to Zork, so when we try to create another historical record for zork, it throws an Integrity Error

**Comment by macro1** [comment]
This is with Django 1.8? I put your case almost verbatim into a test method, and it's not reproducing it. It might be a problem with SQLite not reproducing the correct constraints.

**Comment by KevinGrahamFoster** [comment]
Yes, this occurred on Django 1.8. That's strange, I was using SQLite for it too. I'll try to find more details to repro.

**Comment by KevinGrahamFoster** [comment]
Ok I've updated my original comment... In my test case, I also had "different_data" in Bork. But I'm not sure how it should make a difference.  Perhaps this will help.. I see this in my migrations (last line has the one to one field that's causing the issue):

```
        migrations.CreateModel(
            name='HistoricalZork',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('data', models.IntegerField(default=0, null=True, blank=True)),
                ('different_data', models.IntegerField(default=0, null=True, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
                ('zork_ptr', models.OneToOneField(related_name='+', null=True, db_constraint=False, blank=True, to='blog.Zork')),
            ],
```

**Comment by macro1** [comment]
Figures. `OneToOne` is pretty persistent with its unique constraint. Proposed changes are in #167.
