### ISSUE TITLE
Counts of historical records

### ISSUE THREAD

**Issue by gane5h** [treyhunner/django-simple-history#173]
I'm building a CRM like application. My main model is called "Account" which has an owner_id field. I'm looking to get counts by owner_id as of today (which is simply running an aggregate on Account) as well as counts from history.

Is it possible to query Account.history somehow to get the counts from a month back? If so, what's the best way to achieve this? Thanks.

**Comment by macro1** [comment]
First you would want to narrow down the historical records to the last change for each record that wasn't deleted as of that date. Something like this:

```python
import datetime
import pytz
from django.db.models import Count, F, Max
from accounts import models

as_of = datetime.datetime.now(pytz.utc)

changes_as_of = models.HistoricalAccount.objects.filter(
    history_date__lte=as_of,
)
last_changes = (
    changes
    .exclude(id__in=changes_as_of.filter(history_type='-').values('id'))
    .annotate(Max('history_id'))
    .filter(history_id=F('history_id__max'))
)
```
And the resulting query has both a group-by and a subquery... Which aren't fun. 

Unfortunately we've disabled the related names for all related fields on historical models, so I don't think you can do a count directly on your Owner query like you would with Account. If you never delete accounts, you could filter and count those instead:

```python
models.Owner.filter(account__in=last_changes.values('id')).annotate(Count('account'))
```

At least, I think that'll get you close.

The SQL is kinda fun:
```sql
SELECT "accounts_owner"."id", COUNT("accounts_account"."id") AS "account__count"
FROM "accounts_owner"
INNER JOIN "accounts_account" ON ( "accounts_owner"."id" = "accounts_account"."owner_id" )
WHERE "accounts_account"."id" IN (
 SELECT V0."id" FROM "accounts_historicalaccount" V0
 WHERE (
  V0."history_date" <= 2015-05-01 02:20:05.959962 AND
  NOT (V0."id" IN (
   SELECT U0."id"
   FROM "accounts_historicalaccount" U0
   WHERE (U0."history_date" <= 2015-05-01 02:20:05.959962 AND U0."history_type" = -)
  )) AND NOT (
   V0."id" IN (
    SELECT U0."id" FROM "accounts_historicalaccount" U0
    WHERE (U0."history_date" <= 2015-05-01 02:20:05.959962 AND U0."history_type" = -)
   )
  )
 )
 GROUP BY V0."id", V0."owner_id", V0."history_id", V0."history_date", V0."history_user_id", V0."history_type"
  HAVING V0."history_id" = (MAX(V0."history_id"))
)
GROUP BY "accounts_owner"."id"
```

I think that's right at least. Anyway, bottom line is you probably don't want to do it all in one query.

**Comment by gane5h** [comment]
Wow...fantastic answer @macro1. Let me give this a shot – thanks!
