### ISSUE TITLE
Update documentation about how simple history does not log history when .update() or bulk_create are used

### ISSUE THREAD

**Issue by vinay-kotian** [treyhunner/django-simple-history#174]
When .update() function is used to update a query set result the history of the values changed is not created in the history table. Please can you look into this issue, let me know if any help is required from my end. 
Thank You 
- Vinay Kotian

**Comment by macro1** [comment]
We use the `post_save` signal to trigger new historical records being created. That signal is not fired when `update()` is used instead of `save()`. If you wish to use `update()` for performance reasons, you could create the historical records manually using the `Model.history` manager.

From the [`update()` documentation][https://docs.djangoproject.com/en/dev/ref/models/querysets/#update]:

> ...realize that `update()` does an update at the SQL level and, thus, does not call any `save()` methods on your models, nor does it emit the `pre_save` or `post_save` signals (which are a consequence of calling `Model.save()`). If you want to update a bunch of records for a model that has a custom `save()` method, loop over them and call `save()`...

**Comment by Skyross** [comment]
Hi guys!
Thank you for good package. I used this workaround for my needs. This is example:

```python
from django.utils.timezone import now

class DeletableModelQuerySet(models.QuerySet):
    def update(self, **kwargs):
        if hasattr(self.model, 'history'):
            cache, model = [], None

            for instance in self.all():
                if not model:
                    model = instance.history.model

                attrs = {}
                for field in instance._meta.fields:
                    attrs[field.attname] = getattr(instance, field.attname)

                cache.append(model(history_date=now(), history_type='~', history_user=None, **attrs))

            if model and cache:
                model.objects.bulk_create(cache)

        return super(DeletableModelQuerySet, self).update(**kwargs)

class LogicDeleteManager(models.Manager):
    """
    Model Manager for filtering logical deleted objects
    """
    def get_queryset(self):
        return DeletableModelQuerySet(self.model, using=self._db).filter(deleted=False)

class DeletableModel(models.Model):
    """
    Common model with `soft` deleting. All deletable models should inherit this as base model.
    For `hardware` (real) deletion use objects_with_deleted Model Manager.
    """
    deleted = models.BooleanField(default=False)

    objects = LogicDeleteManager()
    objects_with_deleted = models.Manager()

    class Meta:
        abstract = True

    def delete(self, using=None):
        self.deleted = True
        self.save()

    def real_delete(self, using=None):
        super(DeletableModel, self).delete(using)
```

**Comment by jpatel3** [comment]
@Skyross Whats the work around? I don't see the gist is live anymore.

**Comment by rossmechanic** [comment]
Actually happen to be working on one now. @jpatel3 I'll ping you when it's ready. You can look at https://github.com/treyhunner/django-simple-history/blob/master/simple_history/management/commands/_populate_utils.py#L18 for inspiration in the meantime.

**Comment by rossmechanic** [comment]
@jpatel3 https://github.com/treyhunner/django-simple-history/tree/GH-380-save-history-on-bulk_create that branch has my current implementation for a `bulk_create_with_history` utils function that will bulk_create the objects on the the normal table and the historical table within one atomic transaction. Going to be writing tests and documentation for it and hopefully merge it by EOW. Feel free to copy that locally for the time being.

**Comment by cyzanfar** [comment]
@rossmechanic any updates on the fix for queryset `update` method?

**Comment by rossmechanic** [comment]
@cyzanfar nope. It's not currently a feature we support. It's a little more difficult than bulk create because you don't have the objects in memory to then bulk create on the history table. If you want work on an implementation, I'd be happy to merge it as a utility function

**Comment by jpatel3** [comment]
@rossmechanic Is it available part of 2.7.3? or expected to be released in next one?

**Comment by rossmechanic** [comment]
@jpatel3 no one has implemented it, and it's not high priority for me. If someone wants to implement it, I'd be happy to include it. So it's not part of 2.7.3 but could be part of a future release if someone wants to create a PR for it

**Comment by igorMIA** [comment]
If someone struggles with this issue when adding m2m, I recommend you to use **m2m_changed** signal https://docs.djangoproject.com/en/dev/ref/signals/#m2m-changed
