### ISSUE TITLE
timestamps on Change history are wrong

### ISSUE THREAD

**Issue by bischofs** [treyhunner/django-simple-history#175]
The time changed field on the change history is different from the system time ( hours are wrong , minutes are correct). Why would this value be different than the system time on the server and where could it be set back to the correct time?

**Comment by macro1** [comment]
django-simple-history uses `django.utils.timezone.now()`, which can be configured by your project using the [TIME_ZONE](https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-TIME_ZONE) setting.

If you are not storing timezone-aware dates ([USE_TZ](https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-USE_TZ)), you will need to reprocess the old entries and save them with the correct time.
