### ISSUE TITLE
Recover history programatically

### ISSUE THREAD

**Issue by yguarata** [treyhunner/django-simple-history#176]
Hi there,

is there an option to recover a model history entry programmatically, that is, outside the admin views? My problem is that I need to enable the end users of my application to recover their history entries by their own.

Thanks in advance.

**Comment by macro1** [comment]
There is an `.instance` attribute on every historical object that will provide the correlating instance of the object populated from that point in time.

**Comment by yguarata** [comment]
Thank you!

**Comment by feeh27** [comment]
Hello @macro1,
I'm new to Django.
Could you show me an example of how to recover through the instance?

I was able to retrieve an object, but I do not know how to read its attributes.
The object "Tag object as of 2018-01-12 00:54:04.185437+00:00"

**Comment by rossmechanic** [comment]
Closing this for #322
