### ISSUE TITLE
Model delete

### ISSUE THREAD

**Issue by mr-linch** [treyhunner/django-simple-history#178]
How I can save history records when models delete?

**Comment by macro1** [comment]
This should already be the case... We [have a test](https://github.com/treyhunner/django-simple-history/blob/1.6.1/simple_history/tests/tests/test_models.py#L91) that ensures historical records are created when the model is deleted. Maybe there is something else going on? Are you bulk deleting? All history generation is triggered off of changes to model instances, not querysets.

**Comment by matheusjardimb** [comment]
possibly, @mr-linch is just facing the same scenario as I:

- Create record
- Edit record 
- See history through django admin
- Delete record
- 404 in django admin record

Am I right? Do you want to see the deleted record as part of the record history? (like this https://github.com/treyhunner/django-simple-history/issues/72 )

**Comment by macro1** [comment]
As both #72 is resolved and deletes for instances are already supported I'm closing this. If the untracked deletes are  being performed on querysets, it's a known issue with the way we use signals to track changes, see #174.
