### ISSUE TITLE
RemovedInDjango19Warning

### ISSUE THREAD

**Issue by andyosuna** [treyhunner/django-simple-history#181]
I ran migrate and Django gave me this error three times.
````bash
$ ./manage.py migrate
$VIRTUAL_ENV/local/lib/python2.7/site-packages/simple_history/models.py:9:
RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in
favor of the new application loading system.
  from django.db.models import loading

$VIRTUAL_ENV/local/lib/python2.7/site-packages/simple_history/models.py:14:
RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib, six

$VIRTUAL_ENV/local/lib/python2.7/site-packages/django/contrib/admin/util.py:7:
RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use
django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

````

**Comment by treyhunner** [comment]
Thanks for reporting this @andyosuna!  Those warnings can be safely ignored for now, but we should handle them before 1.9 is released.

What version of Django are you running?

**Comment by treyhunner** [comment]
Also what version of simple history are you on?

**Comment by andyosuna** [comment]
1.8.2 :grimacing: 
simple history 1.6.1

**Comment by treyhunner** [comment]
Ah it looks like there are [changes in the master branch][ch-ch-ch-changes] to remove those warnings that show up on 1.8.

It looks like we need to do a new release to PyPI.

@macro1 I can do a release if you want me to. 1.6.2 or 1.7.0?

[ch-ch-ch-changes]: https://github.com/treyhunner/django-simple-history/compare/1.6.1...master

**Comment by macro1** [comment]
You can do a 1.6.2 release... All it will do is remove warnings. I didn't
release because nothing functionally changed.

**Comment by treyhunner** [comment]
I made a new release to PyPI.
