### ISSUE TITLE
How to create the appropriate history tables for tracked models

### ISSUE THREAD

**Issue by rm-mz** [treyhunner/django-simple-history#192]
Hello,
I followed the quick start instructions having to do with creating history attributes on all tracked models.
But when I go to modify any of those models, I get a databaserror stating: app_historicalmodel does not exist

How do I create these historical tables for each model tracked?

**Comment by macro1** [comment]
Hello @rm-mz!

If you're using South or Django's database migrations (added in Django 1.7) creating these tables should be easy. Just run the make migrations and migrate commands for the app that contains the model that now has a historical model. See [migrations in Django](https://docs.djangoproject.com/en/1.8/topics/migrations/) if you're unfamiliar with them.

You can also generate the create statements using [Django's sql command](https://docs.djangoproject.com/en/1.8/ref/django-admin/#sql-app-label-app-label) if you're not using a db migration tool.

**Comment by rm-mz** [comment]
Thanks macro1
its not quite clear to me what db table columns need to be created by looking at the simple-history models.py. I'm using django 1.5.1 / python 2.7.6
Is there some reference for this in the source that I'm missing here?

**Comment by rm-mz** [comment]
Ah I think I figured out a way!
python manage.py schemamigration tracked_model --auto

Am I on the right track here? By using schemamigration in this way, (along with the necessary source updates to each tracked models.py outlined in the simple-history quickstart guide) should this create the necessary migration files needed to create the necessary simple history tables?

**Comment by macro1** [comment]
Ah, I didn't realize you were on an older version of Django. `python manage.py sql [your_app]` should give you the SQL required to create all of the models for that app. Just grab the tables that start with 'historical'.
