### ISSUE TITLE
Handling bulk_create operations?

### ISSUE THREAD

**Issue by jgbishop** [treyhunner/django-simple-history#194]
Is there a way to handle [bulk_create](https://docs.djangoproject.com/en/1.8/ref/models/querysets/#bulk-create) operations through this plugin? If not, is there a workaround for issuing the necessary signals for these kinds of inserts? I have an application that uses `bulk_create` to keep my database accesses as efficient as possible, but the necessary signals don't get sent, as pointed out in the Django documentation:

> The model’s save() method will not be called, and the pre_save and post_save signals will not be sent.

I found [an article on StackOverflow](http://stackoverflow.com/questions/30632743/how-can-i-use-signals-in-django-bulk-create) that mentions overriding the `bulk_create` method, but I haven't gone down that route yet to see what that yields.

I'm wondering if there's a clever way I can work around this limitation. If I can solve this issue, the simple-history plugin will save my bacon for a project I'm working on. :smile:

**Comment by macro1** [comment]
Not that I'm aware of. With a little extra work you could add your own method to your queryset `bulk_create_with_history()` which could save to both tables with a bulk create.

For ideas you can look at the code the `populate_history` command uses in [`bulk_history_create()`](https://github.com/treyhunner/django-simple-history/blob/1.6.3/simple_history/management/commands/_populate_utils.py#L18).

**Comment by jgbishop** [comment]
How can I programmatically add a record to the corresponding historical table for a given model? I've created a custom QuerySet with a custom method (as you suggested), and I can perform my model's `bulk_create` call, but I don't see how to create instances of the historical model. Is there a call I can utilize to get a historical model for a given model? I see the [get_history_model_for_model](https://github.com/treyhunner/django-simple-history/blob/master/simple_history/management/commands/_populate_utils.py#L8) utility, but is that exposed to me, the end user?

**Comment by macro1** [comment]
That function is to handle cases where we don't know the attribute for the history manager. In your case you can probably just grab the history manager directly off of the queryset model with something like `self.model.history` in your queryset method.

Something like:

```
class BulkHistoryQueryset(Queryset):

    def bulk_create_with_history(self, objs, batch_size=None):
        history_queryset = self.model.history
        
        # create objects in tracked model
        objs = self.bulk_create(objs, batch_size=batch_size)
        
        # create history changes
        history_objs = [history_queryset.model(
            **{field.attname: getattr(instance, field.attname)
               for field in instance._meta.fields}
        ) for obj in objs]
        history_queryset.bulk_create(history_objs, batch_size=batch_size)
```

And then follow the normal steps to make the queryset the default for the default managers for the tracked models.

I didn't run the code at all, make sure you try it out first.

**Comment by jgbishop** [comment]
The `self.model.history` was just the nudge I needed. Thanks for the tip!
