### ISSUE TITLE
Delete old Historical Records

### ISSUE THREAD

**Issue by cleder** [treyhunner/django-simple-history#198]
To keep the history growing too much I'd like to have a function that deletes all historical records older than x days. So the function can be reused in a management command or a celery task

**Comment by robmoorman** [comment]
Also the ability to delete old record via the admin would be nice.

**Comment by michael54** [comment]
:+1:

**Comment by macro1** [comment]
This might go without saying, but doing this with the ORM is pretty easy:

```python
MyModel.history.filter(history_date__lt=timezone.now() - timedelta(days=90)).delete()
```

That should delete all historical records older than 90 days. You could also filter on `history_type` if there was a reason to keep deletions around for audit purposes.

**Comment by nbernardshaw** [comment]
If django-simple-history can self-manage by having the ability to delete old history records, that would be very useful.

**Comment by nikechristo** [comment]
If django-simple-history can self-manage by having the ability to delete old history records, that would be very useful.

**Comment by rossmechanic** [comment]
Dupe of #313
