### ISSUE TITLE
Can't find definition for method `get_previous_by_created_ts`.

### ISSUE THREAD

**Issue by sgallen** [treyhunner/django-simple-history#201]
Assume I have a Model named `Foo`.  I've noticed the `HistoricalFoo` object has a family of methods:
* get_previous_by_created_ts
* get_previous_by_history_date
* get_previous_by_updated_ts
* get_next_by_created_ts
* get_next_by_history_date
* get_next_by_updated_ts

I'd like to look at the definition of these methods but I can't find them in the repo.  

The most I've been able to deduce is that the `Historical*` classes are built using the `create_history_model` of `HistoricalRecords` but I can't figure out when the `get_previous*` and `get_next*` methods are added.

Can someone enlighten me, please?

```
>>> from django.apps import apps
>>> HF = apps.get_model('app1', model_name='HistoricalFoo')
>>> help(HF)
```
This provides:
```
class HistoricalFoo(django.db.models.base.Model)
 |  HistoricalFoo(id, deleted_ts, name, ad_domain, created_ts, updated_ts, company, history_id, history_date, history_user, history_type)
 |
 |  Method resolution order:
 |      HistoricalFoo
 |      django.db.models.base.Model
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __str__ lambda self
 |
 |  get_history_type_display = _curried(*moreargs, **morekwargs)
 |
 |  get_next_by_created_ts = _curried(*moreargs, **morekwargs)
 |
 |  get_next_by_history_date = _curried(*moreargs, **morekwargs)
 |
 |  get_next_by_updated_ts = _curried(*moreargs, **morekwargs)
 |
 |  get_previous_by_created_ts = _curried(*moreargs, **morekwargs)
 |
 |  get_previous_by_history_date = _curried(*moreargs, **morekwargs)
 |
 |  get_previous_by_updated_ts = _curried(*moreargs, **morekwargs)
 |
 |  history_object
 |
 |  revert_url(self)
 |      URL for this change in the default admin site.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
....
```

**Comment by macro1** [comment]
@sgallen: Actually we can't take credit for those. They are part of the [extra instance methods](https://docs.djangoproject.com/en/dev/ref/models/instances/#extra-instance-methods) available on all Django models.

**Comment by sgallen** [comment]
@macro1 Thanks!  My google-fu failed me. =(

**Comment by macro1** [comment]
No problem. I actually wasn't aware that adding a Datetime field would give nice little utility methods like that, so thanks for asking.
