### ISSUE TITLE
admin.site.site_header not respected

### ISSUE THREAD

**Issue by carlostrub** [treyhunner/django-simple-history#205]
If admin.site.site_header is set in urls.py, displaying the history will not respect that and still display "Django administration" as a header.

**Comment by rossmechanic** [comment]
This fix just requires adding `self.admin_site.each_context(request)` to the context within `history_view` and within `history_form_view` on the admin. Good first issue for someone looking to contribute. Will require fixing some tests as well. Django's history view is linked (here)[https://docs.djangoproject.com/en/2.0/_modules/django/contrib/admin/options/#ModelAdmin.history_view]
