### ISSUE TITLE
Simple History Object Tools URL invalid in Django 1.9

### ISSUE THREAD

**Issue by saxbophone** [treyhunner/django-simple-history#206]
Hi, I've recently upgraded an application from Django 1.8.2 -> 1.9.1, and simple_history 1.6.3 -> 1.7.0 respectively.

One thing I noticed is that the link to view an object's history in the admin is broken for every model where I have not overridden the admin object-tools template. 

In 1.9, Django changed an object's detail view from `/admin/<app_name>/<model_name>/<primary_key>/` to `/admin/<app_name>/<model_name>/<primary_key>/change/`.

Rather than linking to `/admin/<app_name>/<model_name>/<primary_key>/history/` as it previously was, the history button now links to `/admin/<app_name>/<model_name>/<primary_key>/change/history/`, which is an invalid URL and raises a HTTP 500 as Django admin change view is trying to interpret everything after the model name as a primary key.

I have this workaround to override the template for the changeforms object tools, which when placed at `templates/admin/change_form.html` will restore the previous behaviour:

```html
{% extends "admin/change_form.html" %}
{% load i18n admin_urls %}
{% block object-tools-items %}
    <li>
        <a href="{% url opts|admin_urlname:'history' original.pk|admin_urlquote %}" class="historylink">{% trans "History" %}</a>
    </li>
{% endblock %}
```

I'm pretty sure this is a bug in simple-history that is a side effect of the new Django 1.9 admin URL structure, although unsure quite why the above fixes it.

It would be great to know (should this bug be identified as valid) what the timescale would be on getting it fixed, I can use the workaround above to get around it just fine but I don't want to deploy my workaround if it is an issue that can be fixed quickly in the library itself.

**Comment by saxbophone** [comment]
Ok, after doing some more research and stumbling upon this issue https://github.com/darklow/django-suit/issues/457 in Django-Suit, which we are also using, I think the source of the problem might actually be there rather than here.

**Comment by saxbophone** [comment]
Sorry for the noise! Closing this now as am confident this is an issue with Django-Suit

**Comment by macro1** [comment]
Thanks for the update @saxbophone! I was a little worried you found a gap in our admin tests.

**Comment by saxbophone** [comment]
No probs @macro1 - again sorry for the noise for what turned out to be a non-issue on your projects part :blush: :relaxed:
