### ISSUE TITLE
Avoid historical entry on delete

### ISSUE THREAD

**Issue by arski** [treyhunner/django-simple-history#207]
Hi there,

Is there a way I can delete a record without a new historical record being created? I'm seeing that regardless if I do delete() on the object or QuerySet, both trigger post_delete.. So I'm wondering if you would agree to adding a skip_history_when_deleting property like in https://github.com/treyhunner/django-simple-history/blob/master/simple_history/models.py#L221 ? I'd be happy to create a PR if you will consider it.

Or would be very happy to hear alternative solutions too.

Thanks!

**Comment by arski** [comment]
@macro1 @luzfcb any thoughts on this? thanks!

**Comment by macro1** [comment]
Hi @arski... Sorry I've taken this long to get back to you.

As you saw, we do not offer an easy way to avoid triggering the delete signal. We are using [Django's post_delete signal](https://docs.djangoproject.com/en/1.9/ref/signals/#post-delete), so you could disable those signals while performing the delete. Another more creative option, if you just don't want any deletes to be recorded for specific models, would be to subclass [`HistoricalRecords`](https://github.com/treyhunner/django-simple-history/blob/1.8.0/simple_history/models.py#L35) and set [`post_delete()`](https://github.com/treyhunner/django-simple-history/blob/1.8.0/simple_history/models.py#L242) to do nothing:

```python
class HistoricalRecordsWithoutDelete(HistoricalRecords):
    def post_delete(self, *args, **kwargs):
        pass
```
I haven't tested that, but I can't think of why it wouldn't work.

**Comment by rocktavious** [comment]
FWIW - I tested this out and it works perfectly
