### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CustomForeignKeyField'

### ISSUE THREAD

**Issue by sheepeatingtaz** [treyhunner/django-simple-history#208]
Apologies if this is documented somewhere, but I cannot see it.

I have an existing Django application that has used django-simple-history from the outset. I am trying to upgrade it to Django 1.9, and as such have also upgraded django-simple-history to 1.7.0. When I try to run runserver to check it, I get the following error when it tries to check migrations, on the 0001_initial.py import on my app:

```
('validation_id', simple_history.models.CustomForeignKeyField(related_name='+', db_constraint=False, default=1981, blank=True, to='enumerations.BankDetailsValid', null=True)),
AttributeError: 'module' object has no attribute 'CustomForeignKeyField'
```

Have I missed something in upgrading? How can I get around this please?

Edit: I can see from looking back at the 1.6.3 release that the CustomForeignField was deprecated, but seeing as it is in an old migration, I don't know how to resolve it?

**Comment by macro1** [comment]
You're right @sheepeatingtaz, that is not documented. `CustomForeignKeyField` was removed in the 1.7 release, as it is no longer needed for representing the `ForeignKey` fields on tracked models. If you do a squash migration with a pre-1.7 version of django-simple-history to remove the import in active migrations, that should resolve the problem.
