### ISSUE TITLE
Does not work with django-modeltranslation

### ISSUE THREAD

**Issue by uolter** [treyhunner/django-simple-history#209]
I am running django 1.9 with model-translation

One of my model has text field description which is also configured in translation.py in order to support multi language:

as soon as I save an instance of my Model I get the following error:

TypeError                                 Traceback (most recent call last)
<ipython-input-3-46a5b65b9cda> in <module>()
----> 1 boat.save()

/Users/uolter/src/sailogy_website_test/sailogy/models.pyc in save(self, *args, **kwargs)
   1572         self._copy_model_specs()
   1573 
-> 1574         super(Boat, self).save(*args, **kwargs)
   1575 
   1576     def get_feedback_info(self):

/Users/uolter/src/sailogy_website_test/venv/lib/python2.7/site-packages/django/db/models/base.pyc in save(self, force_insert, force_update, using, update_fields)
    698 
    699         self.save_base(using=using, force_insert=force_insert,
--> 700                        force_update=force_update, update_fields=update_fields)
    701     save.alters_data = True
    702 

/Users/uolter/src/sailogy_website_test/venv/lib/python2.7/site-packages/django/db/models/base.pyc in save_base(self, raw, force_insert, force_update, using, update_fields)
    735         if not meta.auto_created:
    736             signals.post_save.send(sender=origin, instance=self, created=(not updated),
--> 737                                    update_fields=update_fields, raw=raw, using=using)
    738 
    739     save_base.alters_data = True

/Users/uolter/src/sailogy_website_test/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.pyc in send(self, sender, **named)
    190 
    191         for receiver in self._live_receivers(sender):
--> 192             response = receiver(signal=self, sender=sender, **named)
    193             responses.append((receiver, response))
    194         return responses

/Users/uolter/src/sailogy_website_test/venv/lib/python2.7/site-packages/simple_history/models.pyc in post_save(self, instance, created, **kwargs)
    244             return
    245         if not kwargs.get('raw', False):
--> 246             self.create_historical_record(instance, created and '+' or '~')
    247 
    248     def post_delete(self, instance, **kwargs):

/Users/uolter/src/sailogy_website_test/venv/lib/python2.7/site-packages/simple_history/models.pyc in create_historical_record(self, instance, history_type)
    267         print("attrs ", attrs)
    268         manager.create(history_date=history_date, history_type=history_type,
--> 269                        history_user=history_user, **attrs)
    270 
    271     def get_history_user(self, instance):

/Users/uolter/src/sailogy_website_test/venv/lib/python2.7/site-packages/django/db/models/manager.pyc in manager_method(self, *args, **kwargs)
    120         def create_method(name, method):
    121             def manager_method(self, *args, **kwargs):
--> 122                 return getattr(self.get_queryset(), name)(*args, **kwargs)
    123             manager_method.__name__ = method.__name__
    124             manager_method.__doc__ = method.__doc__

/Users/uolter/src/sailogy_website_test/venv/lib/python2.7/site-packages/django/db/models/query.pyc in create(self, **kwargs)
    397         and returning the created object.
    398         """
--> 399         obj = self.model(**kwargs)
    400         self._for_write = True
    401         obj.save(force_insert=True, using=self.db)

/Users/uolter/src/sailogy_website_test/venv/lib/python2.7/site-packages/django/db/models/base.pyc in __init__(self, *args, **kwargs)
    441                     pass
    442             if kwargs:
--> 443                 raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
    444         super(Model, self).__init__()
    445         signals.post_init.send(sender=self.__class__, instance=self)

TypeError: 'description_de' is an invalid keyword argument for this function

**Comment by macro1** [comment]
Hello @uolter,

Just a stab in the dark here, but does model-translation add fields to the class? If it modifies the model at all, you may have more luck using the [`register()`](https://django-simple-history.readthedocs.org/en/latest/advanced.html#history-for-a-third-party-model) method and calling it right after registering the model with the translator. That might help ensure the new fields are present on the model before simple history builds the historical version of the model.

**Comment by uolter** [comment]
Hello @macro1 ,

just did this Morning what you suggested and it worked to me:

in translation.py  I have:

`
@register(Boat)
class BoatTranslationOptions(TranslationOptions):
    fields = ('description',)
simple_history.register(Boat, inherit=True)
`

with register. 

Thank you !!!

**Comment by loctimize** [comment]
Hello @uolter ,
I came across this issue as I am struggeling wih the same problem. I have a model `CloseReasonTypes` with two fields `name` and `description` that are registered for translation in translation.py.
I followed your advice from Feb 9, 2016 to register the model but get various errors when running `python manage.py makemigrations`:

> class CloseReasonTypesTranslationOptions(TranslationOptions):
> TypeError: 'NoneType' object is not callable

Code in translations.py looks like this

```
import simple_history
from simple_history import register

...

@register(CloseReasonTypes)
class CloseReasonTypesTranslationOptions(TranslationOptions):
    fields = ('name', 'description')

simple_history.register(CloseReasonTypes, inherit=True)

...

translator.register(CloseReasonTypes, CloseReasonTypesTranslationOptions)
```

Any idea what is wrong?
Many thanks!

**Comment by loctimize** [comment]
Last desperate attempt fixed it:

Problem was that I called `simple_history.register(CloseReasonTypes, inherit=True)` too early.
Here is the updated code fragment:

```
import simple_history
# from simple_history import register

...
# @register(CloseReasonTypes)
class CloseReasonTypesTranslationOptions(TranslationOptions):
    fields = ('name', 'description')

...

translator.register(CloseReasonTypes, CloseReasonTypesTranslationOptions)

simple_history.register(CloseReasonTypes, inherit=True)

```

**Comment by lindsayct** [comment]
Hello, 
I tryed used the informaction, but a recived the error:

simple_history.exceptions.MultipleRegistrationsError: customer.Corporation registered multiple times for history tracking.

my file translation.py

`from modeltranslation.translator import (
    translator,
    register,
    TranslationOptions,
)
from simple_history import register
from customer.models import Corporation


#@register(Corporation)
class CorporationTranslationOptions(TranslationOptions):
    fields = ('name', )


translator.register(Corporation, CorporationTranslationOptions, inherit=True)

register(Corporation, inherit=True)`

Any idea what is wrong?
thanks!

**Comment by sharshenaliev** [comment]
raise exceptions.MultipleRegistrationsError(
web_1      | simple_history.exceptions.MultipleRegistrationsError: hub.LandInfo registered multiple times for history tracking.

> Last desperate attempt fixed it:
> 
> Problem was that I called `simple_history.register(CloseReasonTypes, inherit=True)` too early. Here is the updated code fragment:
> 
> ```
> import simple_history
> # from simple_history import register
> 
> ...
> # @register(CloseReasonTypes)
> class CloseReasonTypesTranslationOptions(TranslationOptions):
>     fields = ('name', 'description')
> 
> ...
> 
> translator.register(CloseReasonTypes, CloseReasonTypesTranslationOptions)
> 
> simple_history.register(CloseReasonTypes, inherit=True)
> ```

repeated code, but have error:

raise exceptions.MultipleRegistrationsError(
simple_history.exceptions.MultipleRegistrationsError: hub.LandInfo registered multiple times for history tracking.

how solve this issue?

**Comment by MrArabboy** [comment]
> Hello @macro1 ,
> 
> just did this Morning what you suggested and it worked to me:
> 
> in translation.py I have:
> 
> ` @register(Boat)
> 
> class BoatTranslationOptions(TranslationOptions): fields = ('description',)
> 
> simple_history.register(Boat, inherit=True)
> 
> `
> 
> with register.
> 
> Thank you !!!

if  inherit=True it raise error if one of fields attr is unique=True

**Comment by Paul-Starodub** [comment]
Hello everyone! What is correct code in admin.py in this case?

**Comment by hovi** [comment]
Having the same issue. My model has field with `unique=True` (`autoslug.AutoSlugField`)
Can some of maintainers point me to the right direction? I don't mind creating a fix.

**Comment by oleksandr-cynamics** [comment]
@Paul-Starodub hi, did you manage to fix "simple_history.exceptions.MultipleRegistrationsError: services.Service registered multiple times for history tracking."?

**Comment by mgvs** [comment]
@Paul-Starodub Hi, did you manage to fix this "simple_history.exceptions.MultipleRegistrationsError: services.Service registered multiple times for history tracking."?
