### ISSUE TITLE
History table contains correct user but admin page shows 'admin'

### ISSUE THREAD

**Issue by howardjones** [treyhunner/django-simple-history#210]
Having added a HistoricalRecords() field, and the _history_user() related stuff to one of my models, I am getting legit-looking records in the history table, with the correct user name in my changed_by field, but in the admin site, the history shows 'Admin' for the Changed By column in every change. A db dump confirms that the actual username is there (i.e. not admin).

**Comment by howardjones** [comment]
Now I'm confused... I read this section in the manual: 
http://django-simple-history.readthedocs.org/en/latest/advanced.html#recording-which-user-changed-a-model

and so I implemented the _history_user getter/setter. Then I read the code in models.py for get_history_user(), and it seems that actually you don't want to implement those functions if you want to get the user which changed a model, only if you want to _override_ it?

**Comment by macro1** [comment]
Hello @howardjones.

There are three documented ways to attach users to a tracked change:

1. Use `simple_history.admin.SimpleHistoryAdmin`. Under the hood I believe it makes use of `_history_user`, but it should be as easy as registering your model with that admin class. Good fit if you are only tracking changes made through the admin.
2. Set the `_history_user` attribute yourself. This is probably the one you want if you're making changes to the model in your own application code.
3. Use the middleware. Personally this is a bit magical for me, I'm not a huge fan of this approach. But we have some middleware that keeps track of users attached to the request, and exposes it to the save method: `simple_history.middleware.HistoryRequestMiddleware`

I can see how putting together the different strategies is confusing. The documentation is split into 'quickstart' and 'advanced' to facilitate people looking for a simple solution, but maybe we should have some topic drill-down sections that list all of the available options.

**Comment by howardjones** [comment]
OK - I'm using option 3, and it seems to be working nicely for me now, including web UI and even Django REST Framework accesses (the admin is the 'last resort' for this particular application). Thanks for the clarification! I think something very similar to your reply above would be a useful addition to an introductory section, even if the implementation details are deeper in the manual.
