### ISSUE TITLE
Annotations or comments in the history table

### ISSUE THREAD

**Issue by howardjones** [treyhunner/django-simple-history#214]
I'm interested in using the same history table to record non-change actions, and perhaps some kind of 'comment' field so it's possible to distinguish user-triggered changes from the cascading/internal ones: User 1 modified quantity. User 1 (indirectly) modified shipping total. User 1 (indirectly) modified (order total) - in a presentation of all changes for an order, it would be more readable if it was clear what the application had done, and what the user had done.

With the comments feature, the non-change part could be simply a save() with an appropriate comment attached, too.  obj.save(history_comment="submitted for approval")

**Comment by macro1** [comment]
Related to https://github.com/treyhunner/django-simple-history/pull/152
