### ISSUE TITLE
Foreign Key Constraint fails from unit tests

### ISSUE THREAD

**Issue by howardjones** [treyhunner/django-simple-history#216]
I have some unit tests that create and modify models in the test database, and I get FK constraint failures when the test saves a new model instance:

```
IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test_apptest`.`apptest_historicalprofile`, CONSTRAINT `apptest_history_user_id_34e23bc9_fk_auth_user_id` FOREIGN KEY (`history_user_id`) REFERENCES `auth_use)')
```

I'm using the middleware-based solution to collect the current user, which I guess is part of the reason for this issue (no request is made in the test, so no user to capture), but it looks like the historical\* object allows a Null for the user_id, so what is happening here? And what is the workaround?

(Django 1.9.5, django-simple-history 1.8.0)

**Comment by macro1** [comment]
Hello! This should be fixed in the latest release. Which version of Django
simple history are you using?

**Comment by macro1** [comment]
I missed the version on my phone. Try upgrading to 1.8.1, it should be resolved.

**Comment by clintonb** [comment]
I have confirmed that updating to version 1.8.2 resolved this issue for me.

**Comment by gabn88** [comment]
Please close the issue 👍

**Comment by surfer190** [comment]
I am getting this issue in my tests now with version `1.9.0`:

`django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test_kid_hr`.`users_historicaluser`, CONSTRAINT `users_historicaluser_history_user_id_7f91d047_fk_users_user_id` FOREIGN KEY (`history_user_id`) REFERENCES `users_user` (`id`))')`

What is the fix?

**Comment by rossmechanic** [comment]
@surfer190 what version of Django are you running? Are you still seeing this issue?

**Comment by kingkoma** [comment]
Getting same error when running my tests.
Version 2.0.4
`django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test_weme`.`roles_faces`, CONSTRAINT `roles_faces_role_id_a5ddc8a0_fk_roles_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles_role` (`id`))')`

**Comment by kingkoma** [comment]
Getting same error when running my tests.
Version 2.0.4
`django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test_weme`.`roles_faces`, CONSTRAINT `roles_faces_role_id_a5ddc8a0_fk_roles_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles_role` (`id`))')`

**Comment by kingkoma** [comment]
Getting the same error
Version: 2.0.4

`django.db.utils.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test_weme`.`roles_faces`, CONSTRAINT `roles_faces_role_id_a5ddc8a0_fk_roles_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles_role` (`id`))')
`

**Comment by rossmechanic** [comment]
@kingkoma, my guess is that you're using django-webtest. Look here: https://django-simple-history.readthedocs.io/en/latest/reference.html#using-django-webtest-with-middleware

**Comment by surfer190** [comment]
Thanks @rossmechanic.
