### ISSUE TITLE
'SimpleHistoryAdmin' has no attribute '_meta' in Django 1.9.2

### ISSUE THREAD

**Issue by PabloVallejo** [treyhunner/django-simple-history#218]
I'm setup up the admin for simple history, but when I run the project I get this error: `AttributeError: type object 'SimpleHistoryAdmin' has no attribute '_meta'`. 

The docs show examples for the use without decorator.
```python
#...
admin.site.register(Poll, SimpleHistoryAdmin)
#...
```

But when using in conjunction with `@admin` I get the error.
```python
@admin.register(ProcedureEntry, SimpleHistoryAdmin)
class ProcedureEntryAdmin(admin.ModelAdmin):
    actions = None
    inlines = [ProcedureEntryStatusInline]
```

Any ideas on how to fix it?

Thanks, 

My setup: 
* Django: `1.9.2`
* Django-simple-history: `1.8.1`

**Comment by luzfcb** [comment]
probably the correct code is:

```python
@admin.register(ProcedureEntry)
class ProcedureEntryAdmin(SimpleHistoryAdmin):
    actions = None
    inlines = [ProcedureEntryStatusInline]
```

**Comment by PabloVallejo** [comment]
@luzfcb it works perfect way as `SimpleHistoryAdmin` inherits from `admin.ModelAdmin`.

Thanks 👍
