### ISSUE TITLE
Model with field named 'instance' does not have the instance field in the history table

### ISSUE THREAD

**Issue by nicolasrimmer** [treyhunner/django-simple-history#221]
Hi,
I am using django-simple-history==1.8.1 with python 3.4.2 and Django==1.9.4

I had a model with a field named 'instance' and set-up a history table as per the documentation. All other fields from that model appeared as expected apart from the instance field. When I renamed the field to 'milestone_instance' and did a make migrations the field was correctly added to the model and history table on the database.

Here are some extracts from the migrations directory

0001_initial.py

**instance is in the souce model**
    operations = [
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                **('instance', models.PositiveSmallIntegerField(default=1, help_text='...')),**
                ('iteration', models.PositiveSmallIntegerField(default=1, help_text='...')),
                ('status', models. ....

0005_...py

**Note that instance is missing from the migration to create the history table**
    operations = [
        migrations.CreateModel(
            name='HistoricalProjectMilestone',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('iteration', models.PositiveSmallIntegerField(default=1, help_text='...')),
                ('status', models.CharField ....

0008_...py

**Changing the name in the source model from 'instance' to 'milestone_instance' causes the feild to be added to the history table**
    operations = [
        ...
        migrations.**RenameField**(
            model_name='projectmilestone',
            old_name='**instance**',
            new_name='**milestone_instance**',
        ),
        ...
        migrations.**AddField**(
            model_name='historicalprojectmilestone',
            name='**milestone_instance**',
            field=models.PositiveSmallIntegerField(default=1, help_text='Which (planned) instance of a milestone is this, e.g. RS-A or RS-B. Milestone instances are a sign of the process working'),
        ),

Therefore I think that the migration generation for the history table does not work if the source model field is called 'instance'.

I do not need a fix for this as I have renamed the field but thought I had better let you know.

**Comment by macro1** [comment]
Hi @nicolasrimmer, I'm sorry you had to go through so much before finding a way that things worked for you. I don't know if there is a good way around the issue... Maybe if we had a `get_instance()` function you could pass historical instances to, instead of having a property directly on the instance. At minimum I think this should be documented as a common issue, or a note in the documentation on registering a model with django-simple-history. Thanks for opening the issue!

**Comment by shikopa** [comment]
Is there a workaround for this issue? Trying to incorporate Django Simple History into a Project that already has a Model named 'Instance' that has a Foreign Key relation with a number of Models.

**Comment by shikopa** [comment]
Wrote a wrapper around HistoricalRecord and SimpleHistoryAdmin to get past this.
