### ISSUE TITLE
Support custom auth

### ISSUE THREAD

**Issue by qznc** [treyhunner/django-simple-history#226]
Django's default User model is required. I have custom authentication and removed the default User model.

**Comment by jeffreybrowning** [comment]
This seems like a pretty easy change, `AUTH_USER_MODEL` in place of using Django's auth user model. No response for a year?

**Comment by macro1** [comment]
@jeffreybrowning: I was actually tempted to close the issue a couple times, because as you have seen the project does respect User model swaps. Maybe you were able to identify the issues that @qznc referenced. If you find a solution, please make a pull request, we will be happy to incorporate it.

**Comment by jeffreybrowning** [comment]
Will do.
