### ISSUE TITLE
cannot register simple-history if using modeladmin customization 

### ISSUE THREAD

**Issue by ntorek** [treyhunner/django-simple-history#227]
register() only takes 3 positional arguments ("self" being passed implicitly. If already using a ModelAdmin class to customize the appearance of the model in Django Admin, my registration would look like: 

`admin.site.register(AttorneyGroup, AttorneyGroupAdmin)`

If I want to register SimpleHistoryAdmin, I would be adding a 4th positional argument, like so: 

`admin.site.register(AttorneyGroup, AttorneyGroupAdmin, SimpleHistoryAdmin)`

This raises the following exception: 
`TypeError: register() takes from 2 to 3 positional arguments but 4 were given`

It seems that simple-history cannot be registered if the user is already customizing the model using ModelAdmin.

**Comment by luzfcb** [comment]
your class `AttorneyGroupAdmin` is inheriting from `SimpleHistoryAdmin` instead of `ModelAdmin` ?

```python
from django.contrib import admin
from simple_history.admin import SimpleHistoryAdmin
from . import models 

@admin.register(models.AttorneyGroup)
class AttorneyGroupAdmin(SimpleHistoryAdmin)
    ....
    ....
```

**Comment by ntorek** [comment]
I tried replacing my code with the example you gave, and I am able to migrate without errors and view the Add page on Django Admin. Once I try to save the record I just added, I get the following error though: 

```
AttributeError: 
'AttorneyGroup' object has no attribute 'text'
```

**Comment by luzfcb** [comment]
This last error does not seem to be a error of django-simple-history.
You are sure to have run `python manage.py makemigrations` and than `python manage.py migrate`?

You're probably referencing on `AttorneyGroupAdmin` an attribute called "text" does not exist on `AttorneyGroup` or inside of `AttorneyGroup`

put your model and admin on https://gist.github.com/ and send the link

**Comment by ntorek** [comment]
It was indeed an error in my model code, not in simple-history. I had to change what was written in def __str__() at the end of each model (this was referencing the nonexistent "text") and that fixed it. django-simple-history is now running fine with the fix you suggested earlier. Thank you!

**Comment by luzfcb** [comment]
@ntorek good that you find and solve problem. :-)

if this issue is solved, please, close this issue.
