### ISSUE TITLE
Query previous/next historical entry

### ISSUE THREAD

**Issue by willjschmitt** [treyhunner/django-simple-history#230]
One of the main use cases I've found with django-simple-history has been to get the previous historical entry to calculate deltas in values.

Issue #201 talks about the Django utility functions, which allows for getting the last value by a field. I think it would be great to add a `previous` property to the historical model that grabbed the `get_previous_by_history_date` that reflected the same tracked instance automatically. I feel like a `next` and `previous` method fits perfectly within the historical records context.

As a dependent though, comparing versions between points in time would be excellent, too, but I'll submit a second issue based on response to this.

**Comment by ransford** [comment]
What _is_ the best way, given a historical entry, to get the "previous" entry?

In my use case, `thing` and `thing.history.most_recent()` have the same field values in all cases, except they don't compare identically because `thing._state != thing.history.most_recent()._state`, and `id(thing) != id(thing.history.most_recent())`.

**Comment by SpainTrain** [comment]
@ransford I know this is old, but maybe still useful (or useful to others)

I wrote a function to do this:

```
def get_prev_hist_entry(entry_hist):
    ''' Given a HistoryRecord, return previous record for same instance '''
    entry = entry_hist.instance
    history = entry.history.order_by('history_date')
    hist_list = [hist for hist in history]
    try:
        entry_hist_idx = hist_list.index(entry_hist)
        except ValueError:
            return None
    return hist_list[entry_hist_idx - 1] if entry_hist_idx > -1 else None
```

**Comment by ransford** [comment]
Thank you @SpainTrain!

**Comment by rossmechanic** [comment]
Thanks @SpainTrain . Feel free to add a PR, documentation, and tests for this and I'd be happy to merge.

**Comment by SpainTrain** [comment]
:white_check_mark: https://github.com/treyhunner/django-simple-history/pull/365
