### ISSUE TITLE
MIDDLEWARE_CLASSES setting is deprecated in Django 1.10

### ISSUE THREAD

**Issue by ayharano** [treyhunner/django-simple-history#234]
Hello there.

I am new to django and django-simple-history. I am testing this app and, after following Quick Start and making migrations, I got this warning:

`$ python manage.py makemigrations myapp`
`System check identified some issues:`
`WARNINGS:`
`?: (1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.`

How can the Quick Start guide be changed to use MIDDLEWARE instead of MIDDLEWARE_CLASSES? Or should there be another solution, besides downgrading django to at most 1.9 ?

Thank you very much for your time and effort.

**Comment by macro1** [comment]
Hi @ayharano, thank you for pointing this out. I was not aware the middleware API was updated with 1.10. There are a couple other changes with 1.10 we will need to fix as well, so I will make sure this makes it in.

For now I suggest using Django 1.8 or 1.9 with projects that depend on django-simple-history.
