### ISSUE TITLE
Track only Create (Not Updates or Deletes)

### ISSUE THREAD

**Issue by gudddu** [treyhunner/django-simple-history#235]
Dear All.

Is it possible to track only the "Create" on a Model but not the Updates and Deletes? We are only interested in knowing who created the model instance for certain models.

Regards,
Anurag

**Comment by macro1** [comment]
Hello @gudddu. This isn't exactly a feature... But it looks like setting `skip_history_when_saving = True` on your model as a class attribute might do the trick.

**Comment by gudddu** [comment]
Thanks Micah, It worked like a charm.

Regards,
Anurag

**Comment by macro1** [comment]
Glad to hear!
