### ISSUE TITLE
The no-user placeholder in object history template is not translated

### ISSUE THREAD

**Issue by interDist** [treyhunner/django-simple-history#240]
In [templates/simple_history/object_history.html](https://github.com/treyhunner/django-simple-history/blob/6580dde9f4706cc0637ca131ab664c81ef96b0cf/simple_history/templates/simple_history/object_history.html#L38) the string that indicates an unknown user performing the operation is `None`, instead of `{% trans "None" %}`.

**Comment by rossmechanic** [comment]
Thanks @interDist! Want to submit a fix?

**Comment by rossmechanic** [comment]
Actually, this was already fixed in #256
