### ISSUE TITLE
FieldError: Cannot resolve keyword 'history' into field.

### ISSUE THREAD

**Issue by gthieleb** [treyhunner/django-simple-history#249]
When using history attributes in django-tables2 this works initially to show the history attributes but sorting or filtering in a queryset fails with this error message:

	FieldError at /planning/list
	Cannot resolve keyword u'history' into field. Choices are: name

tried also with this querysets in django shell:

	NameModel.objects.all().order_by('history__most_recent')
	NameModel.objects.all().order_by('history__first__history_user')
	NameModel.objects.all().order_by('history__first__history_date')

models.py

	class NameModel(AbstractMachine):

	    name = models.CharField(max_length=30, blank=True, verbose_name='Name')
	    history = HistoricalRecords()

tables.py:

	class NameTable(tables.Table):

	    created_by = Column('Created By', accessor='history.first.history_user')
	    created = Column('Created', accessor='history.first.history_date')

	    class Meta:
		model = NameModel

settings.py:

	MIDDLEWARE_CLASSES = [
	    'django.middleware.security.SecurityMiddleware',
	    'django.contrib.sessions.middleware.SessionMiddleware',
	    'django.middleware.common.CommonMiddleware',
	    'django.middleware.csrf.CsrfViewMiddleware',
	    'django.contrib.auth.middleware.AuthenticationMiddleware',
	    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	    'django.contrib.messages.middleware.MessageMiddleware',
	    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	    'stronghold.middleware.LoginRequiredMiddleware',
	    'simple_history.middleware.HistoryRequestMiddleware',
	]

**Comment by gthieleb** [comment]
Update:

Seems like django_tables2 does a lot of magic behind the hood when using the accessor attribute. 

I need want a generic approach using the Django ORM. Is it possible to aggregate the history user with aggregate/annotate or do I need to create a CustomManager to lookup the history_user / history_date?

I don't want to create the field explicitly (like documented [here](https://django-simple-history.readthedocs.io/en/latest/advanced.html#custom-history-date)) for each model as this seems to hurt the DRY principles!

**Comment by rossmechanic** [comment]
Not familiar with `django-tables2`. This is a year and a half after you posted, so I assume you found a solution and will close this. If not, feel free to post with a more detailed explanation of what you're looking for and I'm happy to help – it's not clear from your post though. If you did find a solution, feel free to post it here for future users. Thanks.

**Comment by AliYmn** [comment]
Is there an update on the this subject?
