### ISSUE TITLE
Changing history in the admin creates new history objects, rather than updating past history objects.

### ISSUE THREAD

**Issue by wizpig64** [treyhunner/django-simple-history#254]
This problem was introduced [in this commit](https://github.com/treyhunner/django-simple-history/commit/17f4980daa0631ce6c580ea1fe3a254a3bc2bad9#diff-c0731bb75d80f3e6a8efd139f3c5c423L123), and here's why:

- `obj.history.get(pk=version_id).instance.save()` adds a new history object at the current datetime, as if you were calling save on the original `obj`, because `.instance` is a `Obj` type, not a `HistoricalObj` type.
- `obj.history.get(pk=version_id).save()` actually updates the history object itself.

Despite this being a 1-line fix, I don't have a pull request at the moment because it breaks the `test_history_form_view_getting_history` test, and I'm afraid that's a bit over my head. The commit mentioned was also a compatibility fix, and I haven't done any work seeing if this breaks stuff on django versions other than 1.9.

This took a while to figure out because I was getting the same behavior in my own code where I was making the same mistake: `obj.history.as_of(date)`, returns the equivalent of `obj.history.filter(history_date__lte=date).first().instance`, not `obj.history.filter(history_date__lte=date).first()` like I was expecting. (~~It would be super nice to have a `history.as_of(date, instance=False)` method!~~ See pull request #255)

Thanks!

**Comment by rossmechanic** [comment]
As discussed in #255 , closing this issue.
