### ISSUE TITLE
Test is broken in master 

### ISSUE THREAD

**Issue by leportella** [treyhunner/django-simple-history#257]
I just run the tests in the master branch and I am getting this error:

![image](https://cloud.githubusercontent.com/assets/7255297/21688726/1672544e-d355-11e6-9f4b-8e02c953e234.png)

**Comment by macro1** [comment]
@leportella, I'm sorry the tests weren't running for you. The error you're seeing is actually related to a Django 1.10 incompatibility that was in master. I just merged my work on adding Django 1.10 compatibility, so running the tests in master against 1.10 should work now.

Hopefully you find some time to revisit checking out this project!
