### ISSUE TITLE
Does simple-history work well with soft deletes? If so, which soft-deletes library you recommend?

### ISSUE THREAD

**Issue by simkimsia** [treyhunner/django-simple-history#260]
Does simple-history work well with soft deletes? If so, which soft-deletes library you recommend?

**Comment by merwok** [comment]
FWIW, I tested that deleting an instance creates a historical record and deletes from the main table, so I stopped looking for a soft delete solution.  In my case, real delete + history was all good.

I suppose simple_history works with soft-delete libs that are implemented with an extra field, given that simple_history does not modify the original table at all.

**Comment by anomitra** [comment]
What @merwok said, you're not supposed to need a soft-delete thing if you're using simple-history.

**Comment by merwok** [comment]
There is some funky behaviour, like the fact that you can’t see the deleted objects in the admin anymore, unless you build the right URL manually, but I suppose that’s another ticket.
