### ISSUE TITLE
Middleware documentation clarification

### ISSUE THREAD

**Issue by pkaczynski** [treyhunner/django-simple-history#265]
Can you clarify what is the exact functionality of the HistoryRequestMiddleware? Is it suppesed to set history_user for *every* view? Or just admin views? 
The documentation is written in such way, that it suggests every view is affected. However it doesn't seem to work this way, even with history_user methods properly implemented. Works like charm in admin, but nowhere else.

**Comment by macro1** [comment]
It looks like this is a 1.10-specific bug. The `HistoryRequestMiddleware` is not functioning as intended with Django versions 1.10 and later. The test intended to provide coverage is not functioning correctly, it is passing when it should be failing.

Regarding your question about admin vs middleware: Support for user tracking in the admin is provided independent of the middleware. The middleware is intended to be a general solution for automatic user tracking, so 'every view' is the intended behavior.

**Comment by jessemorton** [comment]
Hi there, any update on this issue perchance?

**Comment by rossmechanic** [comment]
@jessemorton Middleware was updated in Django 1.10. [Here] is a link describing how to update pre-Django 1.10-style middleware to work with new versions of django. There are some other issues I need to get to before this, but feel free to make the change and submit a PR.

**Comment by jessemorton** [comment]
@rossmechanic At this point any of the versions of django-simple-history >= 2.0 should automatically save the history_user_id field with the currently logged in user's ID via any view that changes a model that has a `history = HistoricalRecords()` field, is that right? Trying to figure out whether I'm just missing something or whether there's still some issue with the package and Django 1.11 (1.11.9 for me specifically).

**Comment by jessemorton** [comment]
@rossmechanic Resolved it. I went back to the docs and was reminded of the different ways of using it. Using the basic setup things seem to be working automatically. Thanks!
