### ISSUE TITLE
How to set creation date on imported objects?

### ISSUE THREAD

**Issue by Borkason** [treyhunner/django-simple-history#272]
I have to migrate a bunch of mysql records into my Django application. The records already have a creation date and a 'last changed' date.

How do I import those dates into the history field?

I read about the [custom history date field](https://django-simple-history.readthedocs.io/en/latest/advanced.html#custom-history-date), but that is not what I am looking for. I don't want a separate field for the two dates I want to import. I want to have all the information in the history field.

**Comment by joaojunior** [comment]
@Borkason In this case, is necessary you create the history manually. You will need to create an instance of history with `history_type=Created` and set the `history_date' with the creation date and another instance of history with `history_type=Changed` and 'history_date' equals the last changed date.
