### ISSUE TITLE
Exception on UUID ForeignKey

### ISSUE THREAD

**Issue by Informatic** [treyhunner/django-simple-history#278]
Hey!

I'm trying to use django-simple-history together with https://github.com/BertrandBordage/django-tree and UUID-based primary keys/self-referential ForeignKeys.

Right now it seems that ForeignKey in history model is referencing history model (its integer primary key), which causes problems when creating new object, as it tries to cast UUID to integer and it obviously fails.

I'll update this issue later... Just leaving this here so that I don't forget...

**Comment by ckshekhar73** [comment]
I am also facing same issue.
Warning: Out of range value for column 'parent_id' at row 1

**Comment by ckshekhar73** [comment]
Django is  throwing following exception while updating object.
django.db.utils.DataError: (1264, "Out of range value for column 'parent_id' at row 1")
