### ISSUE TITLE
Consider moving this project to jazzband

### ISSUE THREAD

**Issue by treyhunner** [treyhunner/django-simple-history#282]
https://jazzband.co/

Even with semi-active maintainers, it might be helpful to have a more open contribution process as well as the Jazzband roadies to help with maintenance. One of my main concerns is the difference in concerns between different users: each user cares about different versions of Django, different existing features that are important to them, and different new features.

I'm not sure how the deployment situation would change. I'm guessing PyPI access would still be fairly restricted.

Thoughts welcome.

**Comment by claytondaley** [comment]
Found this issue when assessing the level-of-abandonment of several django model audit/history packages.  Second time I've seen the issue raised in as-many months.  Here's a rough framework for how I'd think about it:

 - Anything is better than abandoned.
 - You're delegating control along several dimensions
     - PRs: who can accept something into the repo
     - PyPi: who can push something to PyPi
     - Governance: the process for resolving disagreements about PRs (or PyPi)
     - Administration: the power to enforce governance by revoking rights
 - There are several levels of control (with offsetting time commitments):
     - DIY: Do it yourself (take the time)
     - DTA: Delegate the activity (take the time to vet contributors)
     - DTP: Delegate the power to delegate the activity (take the time to vet the vetters)
     - OPEN: No controls (no time)
 - You've identified two examples of many possible combinations.  I've added two more for illustration, but you could probably find other variants:

| Option | Administration | Governance | PRs |
| --- | --- | --- | --- |
| Current State | DIY | DIY | DIY or DTA |
| Dedicated Org | DIY | DIY or DTA | DTA or DTP |
| YourLabs* | DTP | DTP | DTP |
| Jazzband | DTP | DTP (or OPEN) | OPEN |

*I was vetted and given commit access to [YourLabs](https://github.com/yourlabs) after reporting a security issue in a hosted library.  I didn't even ask for access, but the vetting step provides a good contrast with Jazzband.

 - In any of these models you have to pick a level of control for PyPi, but it should probably parallel the governance model.  It doesn't make sense to have one set of rules for what goes in the repo and another for what is permitted on PyPi.
