### ISSUE TITLE
Start tracking AUTHORS more effectively

### ISSUE THREAD

**Issue by treyhunner** [treyhunner/django-simple-history#285]
Maybe we should start using [octohatrack](https://github.com/LABHR/octohatrack)?

It seems to think we have many more contributors than the ones currently listed.

**Comment by rossmechanic** [comment]
@ThePumpingLemma @barm @kseever what do you guys think? Just tested it out, and it says we have 63 github contributors and >300 total contributors. `octohatrack` includes anyone who adds issues or PR comments to the _All Contributors_ section. Might be nice to give them some recognition (and close out this issue).
