### ISSUE TITLE
Change ugettext to ugettext_lazy?

### ISSUE THREAD

**Issue by cwurld** [treyhunner/django-simple-history#288]
I am using Django signals. This involves putting some imports into the app __init__ file. 

After adding django-simple-history to one of my models, I get this error when starting the dev server:

`django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.`

I believe this error is caused by the ugettext calls in simple_history.models. Is there a reason you chose to use ugettext instead of ugettext_lazy?

**Comment by leportella** [comment]
@cuducos do you have any idea?

**Comment by cuducos** [comment]
I'm sorry about that, @cwurld – no special reason, and I wasn't aware of that issue with signals. I see no problem in changing it to`ugettext_lazy`, @leportella – I just cannot handle that this week, so anyone willing to jump in is more than welcomed ; )

**Comment by merwok** [comment]
> I am using Django signals. This involves putting some imports into the app `__init__` file.

Note that this is fixed in recent Django version with AppConfig: you can import and connect your signal handlers in YourAppConfig.ready, where the app registry is all ready.
