### ISSUE TITLE
"no such column" error

### ISSUE THREAD

**Issue by rgaiacs** [treyhunner/django-simple-history#290]
I'm getting "no such column error" after I updated to 1.9.0. Could we have a note on the release note saying that the user need to run `python manage.py makemigrations`?

**Comment by leportella** [comment]
Did it solve it @rgaiacs ? Making the migration? If so, we can update the docs and release notes

**Comment by treyhunner** [comment]
Good point. A migration was added. Not sure what would be the best way to present that in the release notes.

**Comment by gbataille** [comment]
I think at the very least it should be in the CHANGES.rst in bold.

Additionally, I guess you can
* Document it in the github release notes
* Add an output to the `pip install` command. I know rubygems has specific ways to do it. Seems like pip has nothing built it, but you can add any `print` statements to the `setup.py`...

**Comment by gbataille** [comment]
:wq

**Comment by gbataille** [comment]
I think at the very least it should be in the CHANGES.rst in bold.

Additionally, I guess you can
* Document it in the github release notes
* Add an output to the `pip install` command. I know rubygems has specific ways to do it. Seems like pip has nothing built it, but you can add any `print` statements to the `setup.py`...
