### ISSUE TITLE
Drop Django 1.6 and Python 3.3

### ISSUE THREAD

**Issue by treyhunner** [treyhunner/django-simple-history#292]
Django 1.6 hasn't supported for quite a while: https://www.djangoproject.com/download/#supported-versions

Python 3.3 is likely not used by anyone in production right now. I think Python 3.4 is probably still important to support though.

Django 1.7 isn't supported anymore either. Maybe we should drop it in the release after next?

**Comment by hugovk** [comment]
Here's the pip installs for django-simple-history from PyPI for the last month -- no 3.3!
```
$ pypinfo --percent --pip django-simple-history pyversion
python_version percent download_count
-------------- ------- --------------
2.7              51.9%         10,068
3.5              21.6%          4,199
3.6              14.3%          2,783
3.4              11.9%          2,315
3.7               0.1%             28
None              0.0%              2
2.6               0.0%              2

```

By the way, 3.2 was already dropped so this line can be removed:
https://github.com/treyhunner/django-simple-history/blob/master/setup.py#L30
