### ISSUE TITLE
Documentation item "save without historical record" doesn't render properly

### ISSUE THREAD

**Issue by evertrol** [treyhunner/django-simple-history#293]
The [recent addition to the documentation](https://github.com/treyhunner/django-simple-history/commit/081c04a3491615acf883cd2e3e059e00fa504eee), doesn't render properly.
(The sentence "You want save model without saving a historical record. You can use this method." also doesn't read well. Perhaps "If you want to save a model without a historical record, you can use the following:".)

**Comment by leportella** [comment]
Hi @evertrol ! We invite you to help us keep our documentation in order and updated! Feel free to send us a pull request with the changes! :D
