### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by jhon-palma** [treyhunner/django-simple-history#305]
Hello, good morning, I would like to know if there is any project that can be shared where django-simple-history is used, since I am trying to implement it in my application but I can not access historical information. The lio mio comes at the moment of registering the model, since when I consult the admin, I see the model as is but I do not see who modifies it, nor the date.

Sorry, my english is not good, I use google translate

**Comment by macro1** [comment]
We don't have a demo project right now. What you may be missing, regarding the admin, is that you need to opt-in to seeing history in your admin by [using simple_history.admin.SimpleHistoryAdmin](https://django-simple-history.readthedocs.io/en/latest/usage.html#integration-with-django-admin).
