### ISSUE TITLE
Created manual history records

### ISSUE THREAD

**Issue by SchubmannM** [treyhunner/django-simple-history#307]
Hi, 

I'm using the history model to retrieve the status of an object at a certain point back in time, e.g. 2 months ago, 3 months ago etc. by using the as_of(date) method. 

Now my problem is that we only started recording a specific attribute 4 months ago, so I can't access the state of that attribute from before that. I have all the values in an excel spreadsheet and would like to import them into the HistoryModel, to be able to retrieve their states from a year ago etc. 

Is there any way of doing that?

**Comment by macro1** [comment]
The `HistoryModel`s are actually just normal Django models. You can grab the history queryset and do inserts and updates on it directly.

**Comment by feeh27** [comment]
You can make a change directly in the database table, in case I am using mysql and PHPMyAdmin. The table is always named with a prefix of the app name, historical and the name of the model.  Let's suppose your app is called `appname` and your model is called `Modelname`, the history table will be:

`appname_historicalmodelname`

I hope this helps.
