### ISSUE TITLE
Can't Access the History Detail View of /app/model/<pk>/history/<history_id>

### ISSUE THREAD

**Issue by ranelpadon** [treyhunner/django-simple-history#308]
We have this setup (Django **1.8.18**, SimpleHistory **1.8.2**):
```
# core/models.py
class VersionedAbstractModel(models.Model):
    class Meta:
        abstract = True

    history = HistoricalRecords(inherit=True)


# accounts/models.py
class Brand(VersionedAbstractModel):
    ...

```

So, when I run the `makemigrations`, SimpleHistory migration files will be created in **Accounts** (contains the VersionedAbstractModel child models) and **Core** apps (contains the VersionedAbstractModel parent model). Everything is working fine except when going to the Detail View of particular history objects (e.g. `/accounts/brand/4/history/3/`) since the breadcrumbs in `object_history_form.html` are not resolving properly. It will reference the `/core` admin URL for the Core app (which is non-existent in our case).

Moreover, breadcrumb will switch from `Home › Accounts › Brands › Brand-1 › History` to `Home › Core › Historical Brands › Brand-1 › History › Revert Brand` as you go from history list to history details/revert pages. Hence, it switches scope from **Accounts** app to **Core** app. Unfortunately, we have **NO** non-abstract model registered in our **Core** app and it only contains services/utility/helper functions, plus the migration files for every model due to the inherited VersionedAbstractModel. This issue probably happens when `inherit=True` and/or the involved `parent-child` models are in separate apps/namespaces.

Error Trace:
```
NoReverseMatch at /accounts/brand/4/history/3/
Reverse for 'app_list' with arguments '(u'core',)' and keyword arguments '{}' not found. 
1 pattern(s) tried: [u'(?P<app_label>accounts|events)/$']

In template ~/.virtualenvs/eventcms/eventcms/templates/simple_history/object_history_form.html,
error at line 8:
<a href="{% url "admin:app_list" app_label %}">{{app_label\|capfirst\|escape}}</a> &rsaquo;
```

Possible Workarounds:
1. Create a dummy model in our **Core** app and register it via `admin.site.register()` so that `/core` URL will be registered. However, the dummy model will show in Admin dashboard.
2. Override the `object_history_form.html` and remove the line referencing the **Core** app or the app containing the parent `SimpleHistory` model (i.e. the `VersionedAbstractModel`).

Eventually, we did the item 2 since we have no need for the `/core` URL as of now. It would be great/interesting if you could find a cleaner/simpler solution.

Cheers for this great app! :)

**Comment by macro1** [comment]
I'm guessing this also means that the historical tables have a 'core_' prefix? It looks like our app label testing is a bit light with regards to inherited history tracking:

https://github.com/treyhunner/django-simple-history/blob/1.9.0/simple_history/tests/tests/test_models.py#L378

I'm thinking it's a bug in how the app label is being set. I would expect the historical models to match the models they are registered with.

**Comment by macro1** [comment]
Possibly related to #269
