### ISSUE TITLE
not support update function ?

### ISSUE THREAD

**Issue by pylixm** [treyhunner/django-simple-history#309]
Thanks for your work,first.

I use this lib in my project.When i use it like this `MyModel.objects.all().update(description='test')`,it is not work.

Do I  a wrong way of using?

My environment:
python 2.7 
django 1.7 
django-simple-history 1.9.0

**Comment by kiatweitan** [comment]
Looks like it only works for object.save() but not queryset.update()

**Comment by claytondaley** [comment]
It looks like D-S-H uses signals (e.g. [here](https://github.com/treyhunner/django-simple-history/blob/master/simple_history/models.py#L100)) so you're running into a [known limitation](https://code.djangoproject.com/ticket/12184) of Django (closed as "wontfix").  We use a lot of signals in our system so we always go the route suggested by @kiatweitan.
