### ISSUE TITLE
Accessing Model Methods

### ISSUE THREAD

**Issue by dwasyl** [treyhunner/django-simple-history#311]
I have used `simple-history` to generate a long list of historical objects for a number of objects and made great use of the admin interface. However, as part of a manual compare process, I'd like to use some of the model methods that exist on my model. However, when I try to access them on the `HistoricalModel` it of course reports the functions don't exist.

Is there a way to make use of model methods on Historical objects? The process for turning a `HistrocialModel` into a `Model` isn't stated/clear (unless I've missed something which is certainly possible).

**Comment by macro1** [comment]
You have two options currently:

1. Extend the historical model to have the methods you would like. This can be done with [a custom base class](https://django-simple-history.readthedocs.io/en/latest/advanced.html#change-base-class-of-historicalrecord-models).
2. Use the (apparently undocumented?) `instance` attribute. On any `HistoricalModel`proper instance, there is a `instance` attribute which will make a equivalent `Model` with the data from that point in time. Be very careful though, as saving it will override anything matching that primary key in your `Model` table.

I believe the second approach is what you were looking for.

**Comment by dwasyl** [comment]
Great, thanks @macro1. `instance` did the trick for my need.

Now just to sort out m2m fields and skipping duplicate saves (I had misinterpreted 'excluded_fields' as not saving when there are only changes to those fields).
