### ISSUE TITLE
Include license information in metadata

### ISSUE THREAD

**Issue by Skeen** [treyhunner/django-simple-history#321]
Hello, it appers the license information in the metadata is missing:

    cat site-packages/django_simple_history-1.9.0.dist-info/METADATA

    Metadata-Version: 2.0
    Name: django-simple-history
    Version: 1.9.0
    ...
    License: UNKNOWN

Rather then `UNKNOWN`, perhaps it should say `New BSD` or `Modified BSD`.

**Comment by merwok** [comment]
Technically, License is an optional free-form text field that’s meant to be used if there is no Classifier for the project’s license (django-simple-history has a classifier for license).  In the wild, most projects ignore the spec and define both; it’s harmless as long as the classifier, license field and license file in the repo are the same (including version or variant).
