### ISSUE TITLE
How to revert model outside the admin

### ISSUE THREAD

**Issue by tsolan3** [treyhunner/django-simple-history#322]
So I have a project, in which users should be able to revert to their previous model instances directly from website. So my question is what function is used when clicked revert in django-admin? Or any other way to reach a solution to my issue.

**Comment by rossmechanic** [comment]
@tsolan3 , it looks like the code for that is in `admin.py` here (lines 133-144):
```
form = form_class(request.POST, request.FILES, instance=obj)
            if form.is_valid():
                new_object = self.save_form(request, form, change=True)
                self.save_model(request, new_object, form, change=True)
                form.save_m2m()

                self.log_change(request, new_object,
                                self.construct_change_message(
                                    request, form, formsets))
                return self.response_change(request, new_object)
```

Essentially they just take the old object and save it normally (since save automatically versions). For reverting a model, just grab an old instance of the model and save it.

**Comment by rossmechanic** [comment]
@tsolan3 you can do the following. Say I have an instance of `Poll` called `poll` and I want to revert back to the first version of `poll`. I could do it like this:
```
poll.history.earliest().instance.save()
```
