### ISSUE TITLE
Using populate_history so it works better with migrations

### ISSUE THREAD

**Issue by wontonst** [treyhunner/django-simple-history#326]
I want to bundle populating the history with my migration so that populate_history runs right after migrating the simple models. I have something like

```
def run_populate_history(apps, schema_editor):
    management.call_command("populate_history", "mypackage.MyModel", auto=True)
```

which then gets called in operations

```
        migrations.RunPython(run_populate_history),
```

The problem is that if any migration occurs after this migration which adds or removes a field, then populate_history will fail because the state of the database does not reflect the state of the model. I believe that using app.get_model in the migration would grab the model at the state in db rather than in code which would solve this problem. Is this something that you would be interested in doing?

**Comment by macro1** [comment]
@wontonst I'm not entirely convinced what you're looking for can be done, or would be useful. If you can prove that it would work though, and that current functionality won't be sacrificed, I'm sure we're open to it.

Is your suggested change to update the model that is returned here?
https://github.com/treyhunner/django-simple-history/blob/1.9.0/simple_history/management/commands/_populate_utils.py#L15
