### ISSUE TITLE
Add history to a model via a base class

### ISSUE THREAD

**Issue by joshvillbrandt** [treyhunner/django-simple-history#329]
Howdy! This is probably easy and I'm hoping someone can help me out. I'm trying to add history to models via a shared base class, but this isn't working.

```python
class HistoryModel(models.Model):
    history = HistoricalRecords()

    class Meta:
        abstract = True


class Product(HistoryModel):
    name = models.CharField()


class Order(HistoryModel):
    name = models.CharField()
```

Any suggestions? Maybe we can add this to the [Advanced Usage docs](https://django-simple-history.readthedocs.io/en/latest/advanced.html) once we figure it out.

**Comment by macro1** [comment]
Hey @joshvillbrandt.

This is done with a relatively new feature in django-simple-history:
https://django-simple-history.readthedocs.io/en/latest/advanced.html#allow-tracking-to-be-inherited

The only change I think is needed to your code above is adding `inherit=True` as a parameter to `HistoricalRecords()`.

Let us know if you run into any issues!

**Comment by joshvillbrandt** [comment]
Worked like a charm. Thanks!
