### ISSUE TITLE
Warn when using HistoricalRecords on an abstract class without inherit=True

### ISSUE THREAD

**Issue by konstin** [treyhunner/django-simple-history#341]
Adding a `HistoricalRecords` to an abstract model without `inherit=True` unlike most other Field types doesn't do anything. It should therefore trigger a warning with a hint to `inherit=True`.

```python
class CommonFields(models.Model):
    history = HistoricalRecords()

    class Meta:
        abstract = True

class Foo(CommonFields):
    pass
```

**Comment by shakyasaijal** [comment]
history = HistoricalRecords(inherit = True)

# Reference 
https://github.com/jazzband/django-simple-history/commit/a6fddd67e458badb3bac0bbd68bafeae9707c57c

**Comment by ShedrackGodson** [comment]
```
class ClassName(models.Model):
     history = HistoricalRecords(inherit=True)
```
