### ISSUE TITLE
History of custom UserModel 

### ISSUE THREAD

**Issue by Czaki** [treyhunner/django-simple-history#344]
I try to add to my app history tracking of custom model. To get it working I need to comment history field, then make migrations, then uncomment and again create migrations. in other case Its create History model before User model and there is error in migration. 
Do you have any suggestion how to avoid it? **Or how to debug it?**
 In other models from this app I have split on creating main part of model and Add field with reference. 

Django 2.0, python 3.6, version from branch django-20

**Comment by rossmechanic** [comment]
Maybe check the order in which your apps are imported? Ideally, if you could include the minimum version of your app that includes this bug, I could help with debugging it.
