### ISSUE TITLE
Need for maintainers?

### ISSUE THREAD

**Issue by rossmechanic** [treyhunner/django-simple-history#348]
It looks like this repo could use some help having someone else to look at PRs and maintain. Happy to be included/discuss

**Comment by rossmechanic** [comment]
@treyhunner @macro1

**Comment by maxiplux** [comment]
Hello , thanks for this amazing project , but do you have any news about django 2.0 ?

**Comment by rossmechanic** [comment]
@maxiplux looking into #344 and then going to try to merge by end of next week.
