### ISSUE TITLE
Custom comment

### ISSUE THREAD

**Issue by lk-geimfari** [treyhunner/django-simple-history#350]
Is it possible to use custom comment on changes?

I mean here (4th column):
![screenshot from 2018-03-14 17-15-39](https://user-images.githubusercontent.com/15812620/37407719-5d41d54c-27ab-11e8-92b6-434d4da44298.png)

I have not found information about such feature in docs, but maybe that is undocumented feature?

Thanks!

**Comment by luzfcb** [comment]
@lk-geimfari https://django-simple-history.readthedocs.io/en/latest/advanced.html#change-reason

**Comment by lk-geimfari** [comment]
@luzfcb I mean change it on editing instance in admin.

**Comment by rossmechanic** [comment]
@lk-geimfari you should be able to overwrite the `save_model` method on `SimpleHistoryAdmin` so that you set the change reason before the object is saved. Something like below would work:
```
class MyAdmin(SimpleHistoryAdmin):
    def save_model(self, request, obj, form, change):
         if change:
            obj.changeReason = 'This is the change reason that I want to set'
         super().save_model(request, obj, form, change)
```
