### ISSUE TITLE
Querysets as_for

### ISSUE THREAD

**Issue by torticolix** [treyhunner/django-simple-history#354]
Hi all

I discovered simple-history a few days ago and it fits my needs : have a snapshot of my models along the time
I tried with a simple item model with name and price
I did not find out how to query historical data to get my queryset in the past

For exemple : how to get Items.objects.filter(xxx) or items.objects.all() on Jan 1st 2018 ?

**Comment by rossmechanic** [comment]
`items.history.as_of(datetime.date(2018, 1, 1))` should work.

**Comment by torticolix** [comment]
Yep, but unfortunately it returns a generator, not usable as it to sort, filter or Q , or even use in a cbv ?

**Comment by rossmechanic** [comment]
The code being hit is here on the manager:
```
    def _as_of_set(self, date):
        model = type(self.model().instance)  # a bit of a hack to get the model
        pk_attr = model._meta.pk.name
        queryset = self.get_queryset().filter(history_date__lte=date)
        for original_pk in set(
                queryset.order_by().values_list(pk_attr, flat=True)):
            changes = queryset.filter(**{pk_attr: original_pk})
            last_change = changes.latest('history_date')
            if changes.filter(history_date=last_change.history_date,
                              history_type='-').exists():
                continue
            yield last_change.instance
```
You're welcome to override this and generate the queryset the way you'd like.

**Comment by rossmechanic** [comment]
#229 should also fix this issue. Planning on getting to that PR soon, but feel free to use it as an example of what you can do locally

**Comment by rossmechanic** [comment]
Covered in #397

**Comment by adibo** [comment]
Either I'm not entirely sure what was meant by `as_for`, I reckon the idea was to extend the `history` query capabilities. If so, here is a recipe that could be used:

1. Create a custom `HistoricalRecords` (overwrite descriptor)
2. Create a custom `HistoryDescriptor` (create manager from HistoryQuerySet)
3. Extend `HistoryManager` (define customized `HistoryQuerySet`, add own query methods)
4. Register your django model using your defined custom classes

Steps 1-3: create e.g. `history.py` in your project structure with the `django-simple-history` customizations:
```
# django-simple-history customizations
from simple_history.models import default_get_user, HistoricalRecords
from simple_history.manager import HistoryDescriptor, HistoryManager
import simple_history.utils as utils

class HistoryQuerySet(models.QuerySet):
    """Customized django-simple-history QuerySet"""
    # extend your QuerySet to your liking
    pass


class CustomHistoryDescriptor(HistoryDescriptor):
    """Customized version of django-simple-history HistoryDescriptor"""

    def __get__(self, instance, owner):
        if instance is None:
            return HistoryManager.from_queryset(HistoryQuerySet)(self.model)
        return HistoryManager(self.model, instance)


class CustomHistoricalRecords(HistoricalRecords):
    """Customized HistoricalRecords base class"""

    def __init__(self, verbose_name=None, bases=(models.Model,),
                 user_related_name='+', table_name=None, inherit=False,
                 excluded_fields=None, history_id_field=None,
                 history_change_reason_field=None,
                 user_model=None, get_user=default_get_user,
                 history_descriptor=HistoryDescriptor):
        super(CustomHistoricalRecords, self).__init__(
            verbose_name=verbose_name,
            bases=bases,
            user_related_name=user_related_name,
            table_name=table_name,
            inherit=inherit,
            excluded_fields=excluded_fields,
            history_id_field=history_id_field,
            history_change_reason_field=history_change_reason_field,
            user_model=user_model,
            get_user=get_user)
        self.descriptor_class = history_descriptor

    def finalize(self, sender, **kwargs):
        """Original `finalize` extended by customizing history descriptor"""
        super(CustomHistoricalRecords, self).finalize(sender, **kwargs)

        # get the historical model, overwrite the descriptor
        history_model = utils.get_history_model_for_model(sender)
        descriptor = self.descriptor_class(history_model)
        setattr(sender, self.manager_name, descriptor)
        sender._meta.simple_history_manager_attribute = self.manager_name
```
Step 4: 
```
# in your models.py
from simple_history import register
from history import CustomHistoricalRecords, CustomHistoryDescriptor

# ... YourModel defined here

# register User model with django-simple-history
register(
    YourModel, 
    records_class=CustomHistoricalRecords, 
    inherit=True, 
    history_descriptor=CustomHistoryDescriptor)

```
That's it! You can now extend your `HistoryQuerySet` with any methods you like. 

Note that the Manager operates on the historical version of `YourModel`. Thus, it would be sensible to add a method `to_instances()` (or similar) to convert historical versions of QuerySet objects to the actual model instances (typically to be executed at the end of the query). Still, this will most likely return a generator, not a queryset. For example:
```
class HistoryQuerySet(models.QuerySet):
    """Customized django-simple-history QuerySet"""

    def to_instances(self):
        """Convert historical objects to model instances (via yield)"""
        for historical in self:
            yield historical.instance
```

As a possible improvement (if the above recipe holds) we could consider adding `descriptor_class` as kwargs to `HistoricalRecords` class to simplify the code above (and to allow for customized descriptor).
I hope you find the above useful.
