### ISSUE TITLE
Dropping Support for Django < 1.11

### ISSUE THREAD

**Issue by rossmechanic** [treyhunner/django-simple-history#356]
In accordance with [this](https://www.djangoproject.com/download/#supported-versions), which says that Django is dropping support for Django 1.8 tomorrow, I'm inclined to remove support for Django < 1.11 in the next release (which will include Django 2.0 support). If anyone is opposed to this, let me know.

**Comment by luzfcb** [comment]
since the code to maintain support for django 1.8 does not seem to be large, it would be possible to maintain compatibility until the next LTS, that is, django 2.2? support for python2.7 also ends in 2020.

I have not yet been able to migrate my entire codebase to django >=1.11 and python3

**Comment by rossmechanic** [comment]
@luzfcb I would rather remove support for < 1.11 as Django has also removed support for these versions. As you can see in #320, there are a fair number of changes to make the library compatible with Django < 1.11. I think dropping these versions in the next release will make the codebase cleaner and easier to read and contribute to.  You can continue to use django-simple-history==1.9.1 (I released all the most recent bugfixes/features with the earlier support) and only upgrade to django-simple-history==2.0 when you upgrade your codebase.  As it stands now, `django-simple-history 2.0` will support Django 1.11, 2.0 and python 2.7, 3.4, 3.5, 3.6

**Comment by rossmechanic** [comment]
Now supports Django 1.11 and 2.0
