### ISSUE TITLE
admin does not show history records

### ISSUE THREAD

**Issue by joej** [treyhunner/django-simple-history#357]
Config'ing admin.py as per doc example doesn't change the admin view at all. No history shown, even though there are tracked records.

Recent django 1.11.xx, python 2.7
Using the example to display the 'history' field in the admin.py doesn't change anything vs. 
Model has "history = HistoricalRecords()" and settings config'd and working. The models are autopopulated, and now are tracking each model change as it occurs.

But, the documented example for using SimpleHistoryAdmin doesn't change a single item on the admin page. Nothing. 

Changing back to ModelAdmin works smoothly. Same admin page view. No history of changes.

**Comment by rossmechanic** [comment]
@joej did you try clicking on the history button on the admin change page? That's the only place you should see changes.
