### ISSUE TITLE
Clarity on documentation may required regarding "History for a Third-Party Model"

### ISSUE THREAD

**Issue by mahmudkabir** [treyhunner/django-simple-history#372]
On advanced usage part the "History for a Third-Party Model" [Link](https://django-simple-history.readthedocs.io/en/latest/advanced.html#history-for-a-third-party-model)

it says, "Here’s an example of using simple_history.register to history-track the User model from the django.contrib.auth app" But in file the user will put that code has not been told. 

Can anyone say, where/ in which file the code should go? 

Thanks a lot.

**Comment by mahmudkabir** [comment]
It gives the following error while doing the migration:

> E:\! Project\CMIT\CMITv0101\cmit001>python manage.py makemigrations
> Migrations for 'auth':
>   C:\Program Files\Python36\lib\site-packages\django\contrib\auth\migrations\000
>     - Create model HistoricalUser
> Traceback (most recent call last):
>   File "manage.py", line 22, in <module>
>     execute_from_command_line(sys.argv)
>   File "C:\Program Files\Python36\lib\site-packages\django\core\management\__ini
>     utility.execute()
>   File "C:\Program Files\Python36\lib\site-packages\django\core\management\__ini
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "C:\Program Files\Python36\lib\site-packages\django\core\management\base.
>     self.execute(*args, **cmd_options)
>   File "C:\Program Files\Python36\lib\site-packages\django\core\management\base.
>     output = self.handle(*args, **options)
>   File "C:\Program Files\Python36\lib\site-packages\django\core\management\comma
>     self.write_migration_files(changes)
>   File "C:\Program Files\Python36\lib\site-packages\django\core\management\comma
>     with io.open(writer.path, "w", encoding='utf-8') as fh:
> PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Python36\\lib
>

**Comment by rossmechanic** [comment]
Looks like a windows issue, not a simple-history issue. Maybe try this: https://stackoverflow.com/questions/44044298/permissionerror-errno-13-permission-denied-c-program-files-python35-lib

closing this issue.

**Comment by mahmudkabir** [comment]
not also running on linux too... Can you just confirm that I need to put those codes in models.py? To me, honestly, does not seem so... (but, definitely I could be wrong)

**Comment by rossmechanic** [comment]
https://github.com/rossmechanic/test-django-simple-history/tree/master

Here's a sample app where I register the `User` model in a `models.py` file. Making the migrations and migrating works fine for me.

**Comment by mahmudkabir** [comment]
thats very helpful !

**Comment by mahmudkabir** [comment]
But still not working!

**Comment by rossmechanic** [comment]
You tried running that project locally? What error did you get?

**Comment by mahmudkabir** [comment]
same
