### ISSUE TITLE
History should not be created when model is not dirty

### ISSUE THREAD

**Issue by kunalgrover05** [treyhunner/django-simple-history#386]
If I save the same model multiple times using PUT requests, each time a new History instance is created although there are no diffs. I think there should be a configuration to avoid that.

I also use django-auditlog, and it doesn't capture logs when there is no diff. https://github.com/jjkester/django-auditlog/blob/master/src/auditlog/diff.py#L85

**Comment by rossmechanic** [comment]
Duplicate of #302

**Comment by kunalgrover05** [comment]
Thank you @rossmechanic.

Sorry for missing the duplicate issue.
