### ISSUE TITLE
override the change_form to add few more dependency to display markdown editor in form

### ISSUE THREAD

**Issue by jpatel3** [treyhunner/django-simple-history#389]
We have been using markdown for one of the text field, and for our templates we have added the import of required js/html of polymer component in `change_form.html` under `templates/admin/<app_name>`. As `simple_history` uses regular `change_form.html` template which overrides from `admin/change_form.html` it doesn't render the field in specific format as required. How do we override the `chagne_form.html` for the `simple_history` app?

**Comment by rossmechanic** [comment]
Can you explain this a little more clearly? Are you referring to `object_history_form.html`?

**Comment by jpatel3** [comment]
Yes. I would like to override some field in the form which is displayed using `object_history_form.html`.

For one of the text field, I am returning polymer component, and in order to render it correctly, it needs js/html dependency.

**Comment by rossmechanic** [comment]
So you just want to add the js/html dependency to the page that renders `object_history_form.html`? For the js, you should be able to use something from here https://docs.djangoproject.com/en/2.0/topics/forms/media/. For the html, you can simply overwrite the form the simple history uses (which is set (here)[https://github.com/treyhunner/django-simple-history/blob/master/simple_history/admin.py#L26]). So within the admin you can write
```
class TestAdmin(SimpleHistoryAdmin):
    object_history_form_template = 'templates/admin/<app_name>/simple_history_change_form.html`
```

**Comment by jpatel3** [comment]
Works perfectly fine. Thank you.
