### ISSUE TITLE
Getting migration into own code when registering external app

### ISSUE THREAD

**Issue by finngruwier** [treyhunner/django-simple-history#393]
According to the documentation, registering and 'external' Django model (i. e., a Django model that does not belong to your own code) should be a question of simply putting 'register <externalModel>' somewhere in your code. An example is showed with the django.contrib.auth.User model. In fact this is exactly what I want to do. Unfortunately, the migration file that is created for this step goes into django/contrib/auth/migrations/ and not into a path that I control. This means that the migration is not added to my version control system. If have tried to move the migration into my own code (and manually change its dependencies), but that does not seem to solve the problem.

How can I register django.contrib.auth.Use with Simple History in a way so that the migration goes into my own vcs?

**Comment by rossmechanic** [comment]
You can specify the app that you want the model to be registered in by specifying the `app` parameter. 
```
register(User, app='test_app')
```

**Comment by finngruwier** [comment]
Thanks a lot :-)
