### ISSUE TITLE
Out-of-memory-exception when populating history with management command

### ISSUE THREAD

**Issue by rossmechanic** [treyhunner/django-simple-history#398]
Opening an issue from #335. @markddavidoff had too many model instances and got an out of memory exception. Will open updated PR to fix this issue.

**Comment by markddavidoff** [comment]
I had a PR here? https://github.com/treyhunner/django-simple-history/pull/335 don't see why this was necessary?

**Comment by rossmechanic** [comment]
Sorry didn't see you were still active @markddavidoff. Want to fix the errors and I'll look at it? Closing this issue.
