### ISSUE TITLE
prefetch_related on historical model

### ISSUE THREAD

**Issue by jamiecounsell** [treyhunner/django-simple-history#407]
**Problem Statement**
I need to iterate through many objects, and access properties off their history. This results in thousands of database queries for historical models.

**Describe the solution you'd like**
I'd like a way to prefetch (or even cache) related objects when looking up historical models. I'm really familiar with Django, but not quite at this depth with the Django ORM - I'm not sure it's even practical.

Basically, I'd like to be able to do something like this:

```
class MyModel(models.Model)
    history = HistoricalRecords()
    property = models.CharField(max_length=10)
```

And then

```
objs = MyModel.objects.all().prefetch_related(
    'history'
)
objs.first().history.property # no database query made here
```

Instead, I can only do:
```
objs = MyModel.objects.all()
objs.first().history.property # database query made to get history
```

**Describe alternatives you've considered**
In the meantime, I've used a post_save signal on the objects to precompute and store the value I need. However, I'd like to remove the duplicate information by calculating the value every time it's required.

There's also a related [question](https://stackoverflow.com/questions/45713517/use-prefetch-related-in-django-simple-history) on StackOverflow.

**Comment by rossmechanic** [comment]
Thanks for submitting this @jamiecounsell. Since `history` is a manager rather than a ForeignKey field,  `objs = MyModel.objects.all().prefetch_related('history')` won't work. Right now, we don't have any defined way of implementing your feature, and nothing immediately comes to mind for me as I don't know the ins and outs of how django implements `prefetch_related`. 

You could, however, query the historical table directly, cache the results, and then use the evaluated queryset for your checks. For more on caching and querysets, look [here](https://docs.djangoproject.com/en/1.11/topics/db/queries/#caching-and-querysets). So I'm thinking you could hold the history and query it like this:
```
history_objs = MyModel.history.all()
objs = MyModel.objects.all()

history_for_first_object = filter(lambda x: x.id == objs.first().id, history_objs)
```
That should reduce your total number of queries. Let me know if that works and I can close this. Thanks.

**Comment by jamiecounsell** [comment]
@rossmechanic sounds like a good way to deal with it for now. If I come up with anything else, I'll update here as well. Thanks!

**Comment by mahsa-lotfi92** [comment]
We wanted to show last updated at for each record to return as a field in model Serializer, which needs to get latest history per record. 

To solve this issue I have defined the related_name='histories' for the HistoricalRecord in my model which will made foreign key from history table to my model.

Then I prefetched the histories like this in queryset:
```python3
MyModel.objects.filter(something).prefetch_related(Prefetch('histories', queryset=self.note_model.history.order_by('-history_date'),
                                                to_attr='ordered_histories')
```
And then in the serializer I just retrieved the latest history by this line which does not need to execute any query:
```python3
latest_record = my_model_obj.ordered_histories[0]
```
It works fine now and the number of queries is the same independent of number of objects and response time is much less. The only drawback is if there are a lot of histories, then we may use a lot of memory to prefetch them.

**Comment by RobVeldkamp-TomTom** [comment]
Thanks for providing this @mahsa-lotfi92. However, setting the related_name requires me to provide a default value to populate existing rows with. Did you also deal with that somehow or did you not have any existing rows yet? Any suggestions on how to best resolve this?

**Comment by jokiefer** [comment]
If you got many history entries the payload of the prefetched data becomes big.
If you only need a subset of the histories you can do the following:

#### Scenario
I need only the first and the last history entry to get the created_by, created_at, last_modified_by, last_modified_at attributes for every single list entry.

```python
Prefetch('histories', queryset=MyModel.history.filter(history_type='+').select_related('history_user').only('history_relation', 'history_user__id', 'history_date'), to_attr='first_history'),
Prefetch('histories', queryset=MyModel.history.filter(history_date=MyModel.history.values_list('history_date', flat=True).latest()).select_related('history_user').only( 'history_relation', 'history_user__id', 'history_date').order_by('history_date'), to_attr='last_history'),
```

get the data:

```python

def get_created_at(self, instance):
    return instance.first_history[0].history_date

def get_last_modified_at(self, instance):
    return instance.last_history[0].history_date

def get_created_by(self, instance):
    return instance.first_history[0].history_user

def get_last_modified_by(self, instance):
    return instance.last_history[0].history_user
```

#### Disadvantages 
* Increases queries m*(n+2), BUT they are done in the same batch

#### Advantages
* lower payload of prefetched data

**Comment by rachelmichaels** [comment]
@RobVeldkamp-TomTom did you ever solve this problem? Running into the same issue.
