### ISSUE TITLE
Feature to track changes only and not the creation part.

### ISSUE THREAD

**Issue by tom-riddle** [treyhunner/django-simple-history#409]
**Problem Statement**
I dont want to track the creation records of the model instance.

**Describe the solution you'd like**
I would to track only the update and delete part of the model

**Additional context**
Due to large number of records, I dont want to track the created instance in the history. I already have a created_on date. I believe the changes are getting saved on pre_save signal, so the first instance will be available in the first history record.

**Comment by rossmechanic** [comment]
Hey @tom-riddle, I haven't seen any other demand for this and think it's unlikely to see much demand so I won't add this as an enhancement. However, to implement this in your own codebase, you could extend the `HistoricalRecords` model and overwrite the `post_save` method there. The below should work:

```
class CustomHistoricalRecords(HistoricalRecords):
    def post_save(self, instance, created, **kwargs):
        if created:
            return
        super().post_save(instance, created, **kwargs)
```
