### ISSUE TITLE
Relate generated Historical_x model to their base model

### ISSUE THREAD

**Issue by rorosentrater** [treyhunner/django-simple-history#419]
**Problem Statement**
Forgive me in advance if this is a dumb request/not what simple-history is meant for but,
I have been having a hard time using the generated historical model to filter base model objects. 

I find I have issues when I want to display many base objects based on an aggregation of each base object's history.
Example:

```python
class MyModel(models.Model):
    favorite_letter= models.CharField(max_length=1)
    ...
    history = HistoricalRecords()  # Simple-history
```
Sample data:
**Base model (MyModel)**

id | favorite_letter
------------ | -------------
1 | G
2 | K
3 | W

**Historical model (HistoricalMyModel)**

id | favorite_letter| history_id
------------ | ------------- | -------------
1 | L | 1
1 | G | 3
... | ... | ...
2 | Q | 10
2 | N | 11
2 | W | 12
... | ... | ...
3 | N | 100
3 | W | 101

**Scenario:**
I want to return every MyModel object (base model objects, NOT historical records) that has ever set "N" as their favorite letter (I know the current state of the MyModel object may no longer have this as their CURRENT favorite letter). 

**Problem:**
Currently, I know no way of easily querying a base model's history and returning base model objects with a satisfactory history.

**Desired change:**
I think we should make the generated historical model related to the base model it was created from so you can easily query base model objects by their history. 

**Suggestions?**
If the HistoricalMyModel model had a sort of foreign key relating back to the record it was associated to (1:m) Then we could use the django ORM filter syntax to query this. Something like:
```python
MyModel.objects.all().filter(history__favorite_letter='N')
```
id | favorite_letter
------------ | -------------
2 | K
3 | W

**Comment by rorosentrater** [comment]
So, I'm not adept enough at python or this project to make the PR (pathetic cop out I know sorry!) but I proved to myself that this is possible at least in concept. I edited simple history's `models.py` file in a couple spots to macgyver a foreign key relationship with the base model (I think you guys called it the "concrete model" in the docstrings). I edited `copy_fields()` like this:
```python
def copy_fields(self, model):
    ...
    fields['id'] = models.ForeignKey(model, on_delete=models.CASCADE)
    return fields
```
obviously that is going to break if you don't have an "id" column (Django default PK column), but just bear with me. I also edited `create_historical_record()` to override your nicely constructed `attrs` dict so I can jam an instance reference into my hard-coded id column:
```python
 def create_historical_record(self, instance, history_type):
        history_date = getattr(instance, '_history_date', now())
        history_user = self.get_history_user(instance)
        history_change_reason = getattr(instance, 'changeReason', None)

        manager = getattr(instance, self.manager_name)
        attrs = {}
        for field in self.fields_included(instance):
            attrs[field.attname] = getattr(instance, field.attname)
        attrs['id'] = instance # <- This disgusting thing right here
        manager.create(history_date=history_date, history_type=history_type,
                       history_user=history_user,
                       history_change_reason=history_change_reason, **attrs)
```
Ugly, but it **worked!** I can now make queries using the standard Django ORM syntax that filter and return "concrete model" objects based on their history:
```python
RepairForm.objects.filter(historicalrepairform__incident='abc')
'>>> <QuerySet [<RepairForm: 5ef915af-083a-46ec-8618-88b09c9d04b5>, <RepairForm: 85011a80-c51d-46c6-a06e-30f85d64b76a>]>'
```
Both of those returned concrete models (at some point) had and "incident" of "abc"

Also, diving into the code it seems like you guys intended for a direct relationship between the concrete model and historical model anyways.
```python
    def create_history_model(self, model, inherited):
        """
        Creates a historical model to associate with the model provided.
        """
```
Currently there is no "association" (at least from the DB's perspective). So what do you guys think?

**Comment by rorosentrater** [comment]
Hi @rossmechanic,
Thank you for your snippet, it does solve the problem in my project in a more elegant way than my current work-around.

As for this request, again maybe I am just looking at this *totally* wrong, I haven't used this tech-stack very much let alone this package, but the language you just used makes it seem like you guys **REALLY** want a relation:

> So the foreign key from the historical model to the base model exists by default since the historical table includes all of the fields that are included on the base model. However, since the key is only copied as an integer or a uuid, the db does not know that this is a foreign key.

I get that. I saw that. And I know I can leverage that relationship in a 2-step process using a workaround like the one you just gave that snippet (though that necessitates 2 separate queries no?).

Its just... if we always want that relationship, why not formalize it as a foreign key? You say the foreign key exists but it really doesn't it kind of just "implied." It's not just the db that doesn't know this is a foreign key, the models and by extension the Django ORM don't either.

Sorry if all this is rubbish was a distraction. If having the historical table relate back to the concrete table with a proper foreign key makes no sense, then yes we can close this ticket.

**side note:**
Yeah, you're right. setting `on_delete=models.CASCADE` was probably dumb if these records are supposed to be used like logs.

**Comment by rossmechanic** [comment]
Hi @rorosentrater, the reason we don't use an explicit foreign key is the same reason we drop foreign key constraints on all of the other foreign keys on the historical model. How would we handle the situation in which we delete an instance from the base table? 
Your `on_delete` options are:
1. `CASCADE`: you lose all your historical records
2. `PROTECT`: you won't be able to delete instances from the base table
3. `SET_NULL`: you lose the foreign key, and now there's no way to know which historical record applies to which instance, nor are you able to revert an instance (i.e. undo a deletion)
4. `SET_DEFAULT`: same issue as above
5. `SET`: doesn't help
6. `DO_NOTHING`: you end up with an integrity error because the object doesn't exist. 

As you can see, having an explicit foreign key constraint on the historical table inhibits the functionality of the library, which is why we've avoided it. 

However, we do have the `instance` property on historical objects that allows you to access the base model's instance of that object.

**Comment by rorosentrater** [comment]
Now I see. That makes perfect sense. OK I have been properly schooled, I'll close the issue. Thank you for your time @rossmechanic
