### ISSUE TITLE
Record the IP Address that made a change

### ISSUE THREAD

**Issue by mscansian** [treyhunner/django-simple-history#421]
**Problem Statement**
As described in https://github.com/treyhunner/django-simple-history/issues/420 we use this project for audit. One of the requirements is to record the IP Address that made a change in the system.

**Describe the solution you'd like**
Simple solution: Add IP Address to the history model, update `create_historical_record` to save the REMOTE_ADDR and display it in the admin panel.

**Comment by rossmechanic** [comment]
Use case makes sense to me. Will look at PR by EOW
