### ISSUE TITLE
Migration crash on alter to unique

### ISSUE THREAD

**Issue by jmiguelherazo** [treyhunner/django-simple-history#424]
**Describe the bug**
When you update a model to alter a field to unique=True, makemigration try to alter the same field in the historical model, and crash because it's not unique.

**To Reproduce**
1. Create a model and Adding HistoricalRecords
2. Make multiple update (generate history)
3. Change a model field to be unique
4. Make migrations
5. Migrate

**Expected behavior**
The migration generated must ignore the unique=true in the Historical Model

**Environment (please complete the following information):**
 - Django Simple History Version: 2.3.0
 - Django Version: 2.0

**Comment by jmiguelherazo** [comment]
Yes MySQL 5.6

**Comment by rossmechanic** [comment]
Can you paste in the migrations that are made?

**Comment by jmiguelherazo** [comment]
```
django.db.utils.InternalError: (1061, "Duplicate key name 'provider_historicalmymodel_the_field_4c4025c8'")
```

**Comment by rossmechanic** [comment]
And what MySQL driver are you using with Django?

**Comment by jmiguelherazo** [comment]
I just remember another detail, initially the migration gave me an error because the field I wanted to create as UNIQUE did not have unique values, once I corrected the data in the database and ran the migration again, the error started to appear.

Interpreting better the detail of the error, it is that when failing the first time it did not revert the creation of the index in the historical one, and for that reason it began to fail from there.

**Comment by jmiguelherazo** [comment]
I delete the index created in the first fail and run migrate again and work perfectly.

Thanks for the help, I apologize for the inconvenience.
