### ISSUE TITLE
Warn when using HistoricalRecords on a class by inherit=True and a class inherited by proxy=True

### ISSUE THREAD

**Issue by a-roomana** [treyhunner/django-simple-history#425]
Adding a `HistoricalRecords` to a model by `inherit=True` and a model by `proxy=True` inherited it, create table on database for it!

for example: 

```python
class MyModel(models.Model):
    history = HistoricalRecords(inherit=True)


class ProxyModel(MyModel):
    class Meta:
        proxy = True
```

create table `<app_name>_historicalproxymodel` on database!

**Comment by rossmechanic** [comment]
Not sure what you're saying here. Can you try to explain your problem more clearly?

**Comment by rossmechanic** [comment]
You should only be using the `inherit=True` flag if you're adding `HistoricalRecords` to an abstract model, which you aren't doing here.

**Comment by f3r3nc** [comment]
The proxy model is commonly used to show a particular model on different part's on the admin and django-simple-history creates a historical table for this usage instead of reusing the parent.

**Comment by rossmechanic** [comment]
@f3r3nc I'm well-aware of what a proxy model is. `inherit=True` is only supposed to be used on Abstract models, which it isn't here.
