### ISSUE TITLE
In  the admin, in the history the history_change_reason is not displayed

### ISSUE THREAD

**Issue by eliUni** [treyhunner/django-simple-history#427]
In the admin view, I want to use the historical_change_reason but it's always displayed change

**Expected behavior**
The historical_change_reason field mentionned in the database and not only change

**Screenshots**
![image](https://user-images.githubusercontent.com/39832255/44717355-0e48e800-aabd-11e8-91a2-cad971cec9a4.png)

and in the database
![image](https://user-images.githubusercontent.com/39832255/44717383-23be1200-aabd-11e8-977a-2302355f4392.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser:  Chrome
 - Django Simple History Version: django-simple-history==2.1.1
 - Django Version: Django==1.11.10

**Comment by rossmechanic** [comment]
You can add the `history_change_reason` to the display using the `history_list_display` attribute on the admin class like so:
```
class MyAdminClass(SimpleHistoryAdmin):
    history_list_display = ['id', 'name', 'history_change_reason']
```

However, we should show the `history_change_reason` by default with a better display name, so I will accept this issue and submit a PR.
