### ISSUE TITLE
Model field values change after putting `excluded_fields` in HistoricalRecords

### ISSUE THREAD

**Issue by sunit-poddar** [treyhunner/django-simple-history#433]
I'm using `HistoricalRecords` with my models and adding fields to `excluded_fields`. It saves the data as expected in database but while retrieving in model instances, it jumbles up the data i.e. values gets interchanged.

Example models --
```
class RowInformation(models.Model):
    is_active = models.BooleanField()
    created_at = models.DateTimeField(auto_add_now=True)
    modified_at = models.DateTimeField(auto_now=True)

class ParentModel(RowInformation):
    name = models.CharField(max_length=50, null=False, blank=False)
    age = models.PositiveIntegerField()
    address = models.TextField()
    contact = models.IntegerField()

    history = HistoricalRecords()

    def __str__(self):
        return self.name


class ChildModel(RowInformation):
    parent = models.ForeignKey(ParentModel, on_delete=models.PROTECT)
    name = models.CharField(max_length=50, null=False, blank=False)
    age = models.PositiveIntegerField()

    history = HistoricalRecords()

    def __str__(self):
        return self.name
```
Now while saving, it saves the data right excluding the mentioned fields (checked the database for respective values) but while performing `ChildModel.history.all()`, it messes up the order of values and because of that field with foreign key is holding value for other field's values depending on how many fields i have in `excluded_fields` which leads to exception -
 - `invalid literal for int() with base 10: '<text in field>' if a text field is replacing values
 -  'ParentModel matching query does not exist' if an integer field is replacing values and not in range of existing values in `ParentModel`

Same is the case with `ParentModel.objects.all()` and other field values as well for example `field1`'s value gets changed to some other field's value

I'm guessing this is because `Django Simple History` picks the value from database and puts it in model fields in the same order. (Didn't check the source code hence I could be wrong in this)

**Context**
With the above models when i do `ChildModel.objects.first()` it returns me following data in queryset
```
{'_state': <django.db.models.base.ModelState at 0x7f50fe7ca898>,
 'age': 13,
 'created_at': datetime.datetime(2018, 9, 21, 6, 6, 57, 528544, tzinfo=<UTC>),
 'id': 1,
 'is_active': True,
 'modified_at': datetime.datetime(2018, 9, 21, 6, 6, 57, 528568, tzinfo=<UTC>),
 'name': 'Jimmie Doe',
 'parent_id': 1}
```
and with `ChildModel.history.last()`
```
{'_state': <django.db.models.base.ModelState at 0x7f50fe764f60>,
 'age': 13,
 'created_at': datetime.datetime(2018, 9, 21, 6, 6, 57, 528544, tzinfo=<UTC>),
 'id': 1,
 'is_active': True,
 'modified_at': datetime.datetime(2018, 9, 21, 6, 6, 57, 528568, tzinfo=<UTC>),
 'name': 'Jimmie Doe',
 'parent_id': 1}
```
which is exactly what is expected out of it.
But when i add `excluded_fields` in `HistoricalRecords` i.e. `history = HistoricalRecords(excluded_fields=['modified_at', 'is_active'])` and run the Child model for history -`ChildModel.history.last()`, this is what is get in queryset
```
{'_state': <django.db.models.base.ModelState at 0x7fb7b6f7b2b0>,
 'age': None,
 'created_at': datetime.datetime(2018, 9, 21, 6, 6, 57, 528544, tzinfo=<UTC>),
 'id': 1,
 'is_active': 'Jimmie Doe',
 'modified_at': 1,
 'name': '',
 'parent_id': 13}
```

Please notice how the values of fields have changed for `parent_id` which is my foreign key in this scenario. Also the values of all other fields except for `id` and `created_at`.
Now when I continue to run the above, i get `ParentModel matching query does not exist.` as there's no ParentModel entry with id 13.

**Environment:**
 - OS: Ubuntu 18.04
 - Django Simple History Version: 2.3.0
 - Django Version: 2.1
 - Python version: 3.5.4
 - Database Version: PostgreSQL 9.6.10

**Comment by rossmechanic** [comment]
Not really following what's going wrong here. Can you provide more context about what exactly you're trying to do and when it fails?

**Comment by sunit-poddar** [comment]
I've updated the question with context. My model structure follows the pattern of `RowInformation`, `ParentModel` and `ChildModel`.

**Comment by rossmechanic** [comment]
Is the data still correct in the database? Is it just the query that's returning the wrong data?

**Comment by rossmechanic** [comment]
Weird. I just copied the code over, using django-simple-history==2.3.0 and django=2.1 and couldn't reproduce the issue. If you want to make a sample app that contains the issue in a separate public repo, I can play around with it and try to find the bug. Otherwise, I'll have to close the issue because I couldn't reproduce.

**Comment by sunit-poddar** [comment]
Sure. I'll create a repo and share the same.

**Comment by sunit-poddar** [comment]
I'm closing this issue and raising a proper more clearer issue
