### ISSUE TITLE
HistoricalRecords' iterator fails when used with 'excluded_fields' and 'inherit=True'

### ISSUE THREAD

**Issue by sunit-poddar** [treyhunner/django-simple-history#436]
While working with `django-simple-history`, I came across few interesting enhancements/features/bugs which i'm listing down below -
- How to exclude fields in `abstract inheritance`?
   ```
   class RowInformation(models.Model):
      is_active = models.BooleanField(default=True)
      created_at = models.DateTimeField(auto_add_now=True)
      ...

   class Wallet(RowInformation):
      manufacturer = models.ForeignKey(Manufacturer, on_delete=models.PROTECT)
      total_spent = models.FloatField(default=0)
      ...
   ```
- How to exclude fields in `multitable inheritance`?
   ```
   class RowInformation(models.Model):
      is_active = models.BooleanField(default=True)
      created_at = models.DateTimeField(auto_add_now=True)
      ...

   class Transactions(models.Model):
      amount = models.FloatField()
      mode = models.ChatField(max_length=3, choices=VALID_MODES)
      ...       
      history = HistoricalRecords(inherit=True, excluded_fields=['is_active'])

   class Sales(Transactions, RowInformation):
      vehicle = models.ForeignKey(VehicleInformation, on_delete=models.PROTECT)
      timestamp = models.DateTimeField()
      ...
   ```
- When I'm adding fields to `excluded_fields` to any models for example `Transactions`, it still gets tracked into `TransactionsHistoricalRecords` models. Checked the database for same and database doesn't have those fields but while performing `histories = Sales.objects.first().history.all()`, it fetches excluded fields in `histories` as well.

- Now coming to the real issue from which all these things came up -
  I've a model structure as follows 
  ```
   class RowInformation(models.Model):
      is_active = models.BooleanField(default=True)
      created_at = models.DateTimeField(auto_add_now=True)
      ...

   class Wallet(RowInformation):
      manufacturer = models.ForeignKey(Manufacturer, on_delete=models.PROTECT)
      total_spent = models.FloatField(default=0)
      ...

   class Transactions(RowInformation):
      wallet = models.ForeignKey(Wallet, on_delete=models.PROTECT)
      amount = models.FloatField()
      mode = models.ChatField(max_length=3, choices=VALID_MODES)
      ...       
      history = HistoricalRecords(inherit=True, excluded_fields=['is_active'])

   class Sales(Transactions, RowInformation):
      vehicle = models.ForeignKey(VehicleInformation, on_delete=models.PROTECT)
      timestamp = models.DateTimeField()
      ...
  ```
  When I execute  `histories = Sales.objects.first().history.all()`, throws an error saying `Wallet matching query does not exist` or `invalid literal for int() with base 10: '<text in field>'`.
Checked the above for values in queryset where I noticed -
    - `histories.first().__dict__` has all the values as expected but when i use `self.__dict__` in model's `def __str__(self)`, the values have interchanged.

Please refer to the repo for detailed insight on models and database.

**Public repo to play around with**
Forked a existing public repo - https://github.com/codingforentrepreneurs/Try-Django
- https://github.com/sunit-poddar/sample-django-project

**Project structure**
I've added a EER diagram for whole project. Although please notice the structure of following mentioned models - 
- RowInformation
- Person
- Wallet
- Transactions
- Sales
- Expenditures
- Manufacturer
- VehicleInformation

EER link - https://raw.githubusercontent.com/sunit-poddar/sample-django-project/master/src/try-django-eer-001.png

**To Reproduce in the repo**
1. Clone the repo - https://github.com/sunit-poddar/Try-Django.git
    - Database is already present for your ease of use.
2. Install requirements
2. Run `python manage.py shell`
3. Import models and run -
    - `sales = Sales.obects.first()`
    - `sales.history.all()`

**Environment:**
 - OS: Ubuntu 18.04
 - Django Simple History Version: 2.3.0
 - Django Version: 2.1
 - Python version: 3.5.4
 - Database Version: SQLite

**Comment by rossmechanic** [comment]
Thanks for the detailed description here. Going to play around with it this week and get back to you.

**Comment by sunit-poddar** [comment]
@rossmechanic Were you able to reproduce the error?

**Comment by rossmechanic** [comment]
Hi @sunit-poddar, I was able to reproduce the error. The error you're getting had to do with referencing a ForeignKey from a historical object (where the foreign keys are stored as `int`s to prevent cascading deletes and constraints). If you change the definition of `__str__` on the `Sales` model so that it no longer references `self.wallet`, you won't get the error anymore. So I don't think it has anything to do with excluded fields. 

In fact, the error only occurs when you try to print out the string representation of the object (because of that lack of an explicit foreign key on the history object). If you store that history query in a variable, you can then access it and play with it without any errors (unless you print out the string representation)

**Comment by sunit-poddar** [comment]
@rossmechanic Were you able to reproduce the error?
