### ISSUE TITLE
Improve bulk_history_create

### ISSUE THREAD

**Issue by dgilge** [treyhunner/django-simple-history#442]
**Problem Statement**
1. I love change reasons and you can't set them (without additional db hits).
2. Normally, a history type is defined when a historical record is created. I love consistency.

**Describe the solution you'd like**
1. Adding the following line below that one should do the trick, I think:
https://github.com/treyhunner/django-simple-history/blob/a3b86f101a7a675efd5f979bffa2244f9bcc4c56/simple_history/manager.py#L99
    ```python
    history_change_reason=getattr(instance, 'changeReason', ''),
    ```

2. Adding a keyword argument to `bulk_history_create` called `history_type=''` and then add the following line below the line mentioned in 1.
    ```python
    history_type=history_type,
    ```

**Comment by rossmechanic** [comment]
Fixed by #449
