### ISSUE TITLE
Add Black auto formatter

### ISSUE THREAD

**Issue by barm** [treyhunner/django-simple-history#446]
**Problem Statement**
Currently we don't have an auto formatter, so code style can be inconsistent.

**Describe the solution you'd like**
We like [Black](https://github.com/ambv/black) at Cadre and think we should adopt this to eliminate the need for stylistic comments in code reviews.

**Describe alternatives you've considered**
yapf is another good formatter, but takes longer and uses a heuristic so may not be deterministic.

**Comment by JamesMura** [comment]
Can I work on this ?
