### ISSUE TITLE
Create alias for camel cased `changeReason`

### ISSUE THREAD

**Issue by barm** [treyhunner/django-simple-history#455]
**Problem Statement**
The naming for `changeReason` is camelCase instead of the more Pythonic snake_case. We'd like to move to snake_case for this for consistency.

**Describe the solution you'd like**
Move to snake_case but temporarily maintain backward compatibility so we don't suddenly break downstream projects.

We can make an alias `change_reason` and still accept `changeReason` but warn that it is deprecated for at least one major release.

**Describe alternatives you've considered**
We could alternatively continue to use camelCase, but that's not very nice.

**Comment by rossmechanic** [comment]
Fixed in #655
