### ISSUE TITLE
Registration cycle with custom and historized User model and simple-history 2.5.0

### ISSUE THREAD

**Issue by pm13** [treyhunner/django-simple-history#459]
**Describe the bug**
I have custom user model in module which imports simple_history.models (I think it is common to register historical records in models.py with custom user model.) It worked with simple-history 2.4.0. 

But there is new call of get_user_model on class level (https://github.com/treyhunner/django-simple-history/commit/372632779592b026756cbfd83fc8712afb7a6978). It raises exception:

 File ".../models.py", line ..., in <module>
    import simple_history.models
  File ".../simple_history/models.py", line 29, in <module>
    User = get_user_model()
  File ".../django/contrib/auth/__init__.py", line 170, in get_user_model
    "AUTH_USER_MODEL refers to model '%s' that has not been installed" % settings.AUTH_USER_MODEL
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model '....User' that has not been installed

Class level User variable is used only once - so it is quite simple to call get_user_model in get_extra_fields method (one line down :)) - it solves problem.

**To Reproduce**
1. Define custom user model and import simple_history.models in models.py (for historization of users).
2. Set AUTH_USER_MODEL to this model.

**Environment:**
 - Django Simple History Version: 2.5.0
 - Django Version: 2.1.2

**Comment by rossmechanic** [comment]
Thanks for catching the @pm13. I'll try to merge a bugfix ASAP. Can you describe a little more clearly what fixed the issue? I'm looking at #435 now and also looking at https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#referencing-the-user-model. @ThePumpingLemma think we should just revert that commit based on django docs?

**Comment by rossmechanic** [comment]
Just put up a PR for the fix. Going to have @ThePumpingLemma review and then merge. Should have a release with the fix out by EOD

**Comment by pm13** [comment]
I modify the patch - it was my solution of the problem. It is not full revert but only move of get_user_model.
