### ISSUE TITLE
Setting app_label different to model class 

### ISSUE THREAD

**Issue by uhurusurfa** [treyhunner/django-simple-history#485]
Am I completely missing something or can you only set the **_app_label_** via the register method passing app='some_app'?
I have tried:
history = HistoricalRecords(inherit=False)
   and
history = HistoricalRecords(inherit=True)

... but the app_label in the generated history model is always the same as the model it is created from.
Have traversed the code and see no obvious way to change the generated history model to use a different app_lable than the model from which it is created when creating the history model using the history = HistoricalRecords() mechanism.

This does work:
 register(MyModel, app='some_other_app', inherit=False)

**Comment by rossmechanic** [comment]
You're right. You can only set the app_label of the historical model to be different than the base model using the `register` method. Feel free to add a PR to fix this. Thanks!

**Comment by uhurusurfa** [comment]
Pull request raised: https://github.com/treyhunner/django-simple-history/pull/486
