### ISSUE TITLE
support customise history date base on request context

### ISSUE THREAD

**Issue by s3341458** [treyhunner/django-simple-history#487]
**Problem Statement**
our current project want to  have better support of offline scenarios, so when user updated a object or created a object, it might hit the server much later after user click the button on their device.
In this case, we want to use the client date on its device for history date instead of server date time.

In our case, such client action date time will be provided in request headers.
so we hope there is a easy way for history to support custom date from request context.

**Describe the solution you'd like**
extract history_date = getattr(instance, "_history_date", now()) into a method, so we can customised it by 
overwrite it through inheritance.

**Describe alternatives you've considered**
like 'default_get_user' support 'default_get_history_date(request, **kwargs)', so we can customise it by passing function on construction time.

**Comment by rossmechanic** [comment]
Hi @s3341458, you should be able to use pre and post hooks on the historical save to edit the history date. This should be better documented, so I'll create an issue for adding documentation there. 

Look here for the hooks: https://github.com/treyhunner/django-simple-history/blob/master/simple_history/models.py#L376
