### ISSUE TITLE
Can't use .prev_record and .next_record when using not default field name

### ISSUE THREAD

**Issue by yetanotherape** [treyhunner/django-simple-history#500]
I'm using not default field name for HistoricalRecords:
```
class Record(models.Model)
...
log = HistoricalRecords()
```
When I try to use .prev_record or .next_record property of the history object if fails with a message "AttributeError: 'Record' object has no attribute 'history'". It seems that 'history' attribute is hardcoded now.

**Environment:**
 - OS: Ubuntu 16.04
 - Django Simple History Version: 2.5.1
 - Django Version: 1.11.17
 - Database Version: MySQL 5.7

**Comment by rossmechanic** [comment]
Just released `2.6.0` with this bug fix included

**Comment by yetanotherape** [comment]
@rossmechanic Super fast! Thanks a lot!!
