### ISSUE TITLE
Does DSH work with factory_boy ?

### ISSUE THREAD

**Issue by atodorov** [treyhunner/django-simple-history#519]
I'm in the middle of quite a big change for Kiwi TCMS which uses `model_obj.history.latest().history_id` in a few places. This all seems to work fine at runtime when I exercise the pages manually.

However the automated test suite fails and debugging shows me there are 0 history objects in the test DB. I am using factory_boy to create model objects for tests so not sure how well that plays with simple-history.

Some comment is greatly appreciated since I have no idea how to proceed.

**Comment by dgilge** [comment]
I'm using these two apps without any problems. Maybe you're creating your objects with a bulk operation which doesn't call `save`?

**Comment by atodorov** [comment]
> I'm using these two apps without any problems. Maybe you're creating your objects with a bulk operation which doesn't call save?

Nope, but I am using `TestCaseRunFactory(....)` to create my test objects and I'm not sure if that calls `save()`. Calling `factory_obj.save()` worked around the missing historical records.
