### ISSUE TITLE
Error when method __str__ points to a foreign key

### ISSUE THREAD

**Issue by thiagoabreudev** [treyhunner/django-simple-history#521]
**Error when method __str__ points to a foreign key**

> Traceback (most recent call last):
  File "/home/thiago/workspace/aprendendo/teste-simple-history/tasks/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 178, in __get__
    rel_obj = getattr(instance, self.cache_name)
AttributeError: 'Task' object has no attribute '_type_task_cache'

**The code below shows the problem:**

```
from django.db import models
from simple_history.models import HistoricalRecords


class TypeTask(models.Model):
	name = models.CharField(verbose_name='Type Task', max_length=255)


class Task(models.Model):
	type_task = models.ForeignKey(TypeTask, verbose_name='Type task', on_delete=models.PROTECT)
	task_date = models.DateTimeField(verbose_name='Date of task', auto_now=True)
	task_status = models.CharField(verbose_name='TaskStatus', max_length=255)
	history = HistoricalRecords(excluded_fields=['type_task', 'task_date'])

	def __str__(self):
		return str(self.type_task.name)
```

**Steps to reproduce the behavior:**
1. Go to 'Django shell'
2. Run
```
from core.models import TypeTask, Task
type_task = TypeTask.objects.create(name='Online')
task = Task.objects.create(type_task=type_task, task_status='OPEN')
task.history.all()
```

**Environment:**
 - Django Simple History Version: [e.g. 2.7.0]
 - Django Version: [e.g. 1.11.18]

**Additional context**

 - if the __str__ method does not return a foreign key field the problem does not occur

**Comment by rossmechanic** [comment]
The issue is that your historical model inherits its `__str__` method from your base model but you've excluded `type_task` from your historical model, so it has no foreign key to check. If you include `type_task` in your history you should no longer see the error.
