### ISSUE TITLE
I try django-simple-history with django 2.1.4 but it is showing internal server error. 

### ISSUE THREAD

**Issue by Akashutreja** [treyhunner/django-simple-history#525]
Hi,
I am trying to use django-simple-history but when I run it on production server it started showing me Internal server error.
Please help me out.
Here is my settings.py file code 

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    'simple_history',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

```

And model in which  i am using it as 
```
class Employee(models.Model):
    DateOfResignation = models.TextField(blank=True, null=True)
    LastWorkingDay = models.TextField(blank=True, null=True)
    DateOfDeletion = models.DateTimeField(default=datetime.datetime.utcnow, blank=True, null=True)
    ChangedBy = models.TextField(blank=True, null=True)
    history = HistoricalRecords()
    __history_date = datetime.datetime.utcnow()

    @property
    def _history_date(self):
        return self.__history_date

    @_history_date.setter
    def _history_date(self, value):
        self.__history_date = datetime.datetime.utcnow()

```

And the error which I am getting is.
**Internal Server Error**
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at you@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by rossmechanic** [comment]
Hi @Akashutreja, this doesn't seem to be an issue with the library so please direct your questions to https://stackoverflow.com/questions/tagged/django-simple-history. You'll probably have an easier time debugging this with debug=True, so that you can see the stack trace rather than just an internal server error. Closing this unless an actual issue with django-simple-history is pointed out.
