### ISSUE TITLE
Foreign Key value in __str__ results in error.

### ISSUE THREAD

**Issue by dojutsu-user** [treyhunner/django-simple-history#533]
**Describe the bug**
I have two models like this:
```python3
class Book(models.Model):
    title = models.CharField(max_length=50)
    # other fields

class BookCode(models.Model):
    book_id = models.CharField(max_length=10)
    associated_book = models.ForeignKey(Book, on_delete=models.CASCADE)
    history = HistoricalRecords()
    # other fields

    def __str__(self):
        return f'[{self.book_id.upper}] {self.associated_book.title}'
```

When I try to get the history of model `BookCode`, this happens
```
>>> BookCode.history.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pikachu/Desktop/Practice/library/venv/lib/python3.6/site-packages/django/db/models/query.py", line 247, in __repr__
    return '<%s %r>' % (self.__class__.__name__, data)
  File "/home/pikachu/Desktop/Practice/library/venv/lib/python3.6/site-packages/django/db/models/base.py", line 503, in __repr__
    return '<%s: %s>' % (self.__class__.__name__, self)
  File "/home/pikachu/Desktop/Practice/library/venv/lib/python3.6/site-packages/simple_history/models.py", line 386, in <lambda>
    self.history_object, self.history_date
  File "/home/pikachu/Desktop/Practice/library/portal/books/models.py", line 84, in __str__
    return f'[{self.book_id.upper()}] {self.associated_book.title}'
  File "/home/pikachu/Desktop/Practice/library/venv/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 188, in __get__
    "%s has no %s." % (self.field.model.__name__, self.field.name)
books.models.BookCode.associated_book.RelatedObjectDoesNotExist: BookCode has no associated_book.
```

**Expected behavior**
Model history should be the output.

**Environment:**
 - OS: Ubuntu 18.04.2 LTS
 - Django Simple History Version: 2.7.0
 - Django Version: 2.1.7
 - Database Version: Using default `sqlite3`.

**Comment by rossmechanic** [comment]
Hi @dojutsu-user, the reason this fails is that the `__str__` method for `HistoricalBookCode` is inherited from `BookCode`. `HistoricalBookCode` removed database constraints from its foreign keys, so `HistoricalBookCode` won't actually have an `associated_book`, so when you try to get the `history` for `BookCode` in your console, it fails. If you change the `__str__` method so that it doesn't traverse any foreign keys, it'll fix the problem. Your other option would be to submit a PR to have a custom `__str__` method for the history.

**Comment by alejandro-perez** [comment]
I have a similar issue, that also results in a performance issue when listing a lot of changes.
If one has a __str__() method that uses a ForeignKey, it will never works if the releated object has been removed, and also it will require a DB query for each element (apparently select_related() does not work here).

My suggestion is that a HistoricalRecord stores has a field called `repr` containing the textual representation of the object at the time the record was created.

If this sounds insteresting I can try to create a PR for it
