### ISSUE TITLE
Specify history_type for custom model methods

### ISSUE THREAD

**Issue by bencleary** [treyhunner/django-simple-history#534]
**Problem Statement**
If this is already in please just close it off and point me in the right direction. A model i was working on used soft deleting, just by updating the model instance itself. When marking this as deleted by default it actions it as record change not record deleted.

**Describe the solution you'd like**
I appreciate this is probably a niche problem but soemthing to solve it was to modify the create_historial_record method, i have implemented a similar method to the changeReason implementation.

```python 
    def create_historical_record(self, instance, history_type):
        if hasattr(instance, 'changeType'):
            history_type = getattr(instance, 'changeType', history_type)
        history_date = getattr(instance, '_history_date', now())
        history_user = self.get_history_user(instance)
        history_change_reason = getattr(instance, 'changeReason', None)
        manager = getattr(instance, self.manager_name)
```

**Describe alternatives you've considered**
None

**Additional context**
Source Code
![image](https://user-images.githubusercontent.com/11590157/53962131-3192c680-40e2-11e9-89ed-9614e0119394.png)

Model Instance
![image](https://user-images.githubusercontent.com/11590157/53962174-4707f080-40e2-11e9-8dfe-8b445f3866de.png)

**Comment by rossmechanic** [comment]
Hi @bencleary. You can simply use the `pre_create_historical_record` hook in order to update the `history_type` before history is saved. https://django-simple-history.readthedocs.io/en/2.7.0/signals.html
