### ISSUE TITLE
History Info for Django User Related Tables

### ISSUE THREAD

**Issue by surya534** [treyhunner/django-simple-history#535]
**Problem Statement**
I am using django User model for creating and managing users. I want to track history of these tables also. If i update Permissions/Groups to User regularly then History table for auth_group, auth_permissions etc.

Is there a way right now ? I dont see anything in documentation

**Comment by erikvw** [comment]
hi @surya534 

although i have never tried this, i would carefully review the django docs on specifying a [custom user model](https://docs.djangoproject.com/en/2.1/topics/auth/customizing/#specifying-a-custom-user-model).

if still something you want to do, then try adding the history manager to your custom user model.
