### ISSUE TITLE
clean_duplicate_history doesn't respect history field name

### ISSUE THREAD

**Issue by yetanotherape** [treyhunner/django-simple-history#540]
I'm using not default field name for HistoricalRecords:
```
class Record(models.Model)
...
log = HistoricalRecords()
```
When I run `clean_duplicate_history` if fails with a message "AttributeError: ... object has no attribute 'diff_against'". It seems that 'history' attribute is hardcoded.

**Environment:**
 - OS: Ubuntu 16.04
 - Django Simple History Version: 2.7.0
 - Django Version: 1.11.20
 - Database Version: MySQL 5.7

**Comment by rossmechanic** [comment]
Thanks for raising this bug @yetanotherape. We can fix that by using `utils.get_history_manager_for_model` instead of hardcoding `history` there. If you want to add a PR for that with tests, I'd be happy to merge.

**Comment by rossmechanic** [comment]
Closed by #542
