### ISSUE TITLE
What is the best way to track Read events on operational models?

### ISSUE THREAD

**Issue by dopatraman** [treyhunner/django-simple-history#541]
**Problem Statement**
This library does an excellent job of tracking CUD events, but does not support auditing Read events. I understand that most users probably don't need this, but it would be useful to have.

**Describe the solution you'd like**
Allow an option for the `HistoricalRecords` constructor that instructs the library to record read events on operational tables.

**Describe alternatives you've considered**
Currently, I'm trying to log reads by hooking into Django's manager api:
```
class MyManager(models.Manager):
    def get_queryset(self):
        self._log_read()
        return super().get_queryset()

    def _log_read(self):
        historical_model = self.model.history.model
        attrs = {
            'id': getattr(self.model, 'id')
        }
        read_record = historical_model(
                history_date=datetime.now(),
                history_type='R',
                history_user=request.thread_local.current_request.user,
                history_change_reason='reading',
                **attrs
            )
        read_record.save()
```

However, this produces an error, because the `id` passed into the `historical_model` constructor is of the type `django.db.models.query_utils.DeferredAttribute`.

**Comment by rossmechanic** [comment]
Hey @dopatraman thanks for your contribution. Don't think this falls within the scope of DSH (and it would be pretty difficult to implement, as DSH relies entirely on post_save hooks for tracking history). Going to close this issue unless convinced otherwise.
