### ISSUE TITLE
Can't retrieve absolute URL of history objects

### ISSUE THREAD

**Issue by richardcornish** [treyhunner/django-simple-history#551]
**Describe the bug**
Can't retrieve a history object.

**To Reproduce**
I created a basic `DetailView` but I can't figure out the queryset to retrieve it from a URL that is similar to the admin, i.e. `/admin/loglines/logline/1/history/3/`. My use case seems fairly simple, just 

```
class LoglineHistoryDetailView(DetailView):
    template_name = 'loglines/logline_detail_history.html'

    def get_queryset(self):
        return Logline.history.filter(history_id=self.kwargs['history_pk'])
```

My URLs:

```
urlpatterns = [
    path('<int:pk>/history/<int:history_pk>/', LoglineHistoryDetailView.as_view(), name='logline_detail_history'),
    path('<int:pk>/', LoglineDetailView.as_view(), name='logline_detail'),
]
```

The correct SQL from the admin displays:

```
SELECT ••• FROM "loglines_historicallogline" WHERE ("loglines_historicallogline"."history_id" = '3' AND "loglines_historicallogline"."id" = '1')
```

My SQL ends up as:

```
SELECT ••• FROM "loglines_historicallogline" WHERE ("loglines_historicallogline"."history_id" = '3' AND "loglines_historicallogline"."history_id" = '1')
```

There seems to be some pre-querying happening in the `history` manager, but the source code is fairly obscure.

**Expected behavior**
Retrieve the object and display a template.

**Comment by rossmechanic** [comment]
Hi @richardcornish , trying to figure out exactly what's going on here. Should your queryset be `Logline.history.filter(history_id=self.kwargs['history_pk'], id=self.kwargs['pk'])` to begin with?

**Comment by richardcornish** [comment]
@rossmechanic Thanks for the quick response. I think I was able to figure it out.

My original queryset is `Logline.history.filter(history_id=self.kwargs['history_pk'])`, and because `DetailView` makes the assumption that a queryset should be able to [filter further down via its `pk` attribute](https://github.com/django/django/blob/2.2/django/views/generic/detail.py#L36), becoming `Logline.history.filter(history_id=self.kwargs['history_pk']).filter(pk=self.kwargs['pk'])`.

The problem seems to be that the `history` manager equates `pk` with `history_id`, which actually results in `Logline.history.filter(history_id=3, history_id=1)`, which would not be possible.

Django doesn't have a [`slug_field`](https://github.com/django/django/blob/2.2/django/views/generic/detail.py#L41) equivalent for `pk` attributes (which in this case might read `pk_field = 'id'` or even `pk_field = self.model._meta.pk.attname`), and so a full override in `DetailView` of `get_object` worked:

```
class LoglineHistoryDetailView(DetailView):
    template_name = 'loglines/logline_detail_history.html'

    def get_object(self, queryset=None):
        return Logline.history.get(id=self.kwargs['pk'], history_id=self.kwargs['history_pk'])
```
