### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by nick-traeger** [treyhunner/django-simple-history#552]
**Describe the bug**
It looks as if the new version lacks the dependency on module six.

**To Reproduce**
1. pip install django-simple-history
2. python manage.py makemigrations

**Expected behavior**
A running system

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux Mint 
 - Browser (if applicable): chrome
 - Django Simple History Version: 2.7.1
 - Django Version: 2.2
 - Database Version: sqlite3

**Additional context**
Tested with an old and a new environment

**Comment by december1981** [comment]
Presumably, this can be fixed by adding

```
install_requires=[
    'six',
],
```

to setup.py

**Comment by rossmechanic** [comment]
Ah, sorry @nick-traeger . I'll release a patch for that today. Should be fine if you just `pip install six`
