### ISSUE TITLE
Limit history rows

### ISSUE THREAD

**Issue by nicolaetelecine** [treyhunner/django-simple-history#554]
**Problem Statement**
Hi, 
by default, history rows are not limited?
currenty it is a way to limit the history rows?

**Describe the solution you'd like**
Add new parameter limit, example:
history = HistoricalRecords(cascade_delete_history=True, limit=10)
That will keep only 10 history rows, older will be delete.

Thank you,
Nicolae

**Comment by rossmechanic** [comment]
Hi @nicolaetelecine, I'm not convinced this is a feature we need, but you could always run a job that goes and cleans up history at a periodic basis. going to close this issue unless convinced otherwise

**Comment by erikvw** [comment]
@nicolaetelecine I agree with @rossmechanic  that this is better handled as a housekeeping task (e.g. celery). But DSH allows you to use a custom model class for the historical model. You could pass a custom model class to the `HistoricalRecords` manager and let the custom model class handle the LIFO feature, possibly in the `save` method. For example:

```
class LifoModel(models.Model):
    def save(self, *args, **kwargs):
        # code for my feature ...
        super().save(*args, **kwargs)

    class Meta:
        abstract = True

```

`history = HistoricalRecords(bases=(LifoModel,))
`

**Comment by nicolaetelecine** [comment]
Thank you for recommendations !!!
