### ISSUE TITLE
Problem upgrading from 1.9.0 to 2.5.0

### ISSUE THREAD

**Issue by alecvn** [treyhunner/django-simple-history#570]
We have an older project which we are in the process of upgrading from version 1.9.0 to 2.5.0.  It's quite a far reaching upgrade of the project and includes the Python 3 and Django 11 upgrade as well.  When running any Django management command however we get `AttributeError: module 'simple_history.models' has no attribute 'HistoricalRecords'`.

**Environment:**
 - OS: Ubuntu 18.04
 - Django Simple History Version: 2.5.0 (from 1.9.0)
 - Django Version: 1.11.3 (from 1.9.12)
 - Database Version: PostgreSQL 9.5.4

**Additional context**
We are running the entire environment on docker.

**Comment by alec-implicitdesign** [comment]
An upgrade to `django-simple-history 2.7.2` worked.  So I believe there might be an issue with `2.5.0`.

**Comment by rossmechanic** [comment]
Hm, unsure. But if 2.7.2 worked, I'm satisfied.
