### ISSUE TITLE
diff_against doesn't detect changes to parent model attributes when using inherited models

### ISSUE THREAD

**Issue by marcanuy** [treyhunner/django-simple-history#575]
**Describe the bug**
`HistoricalChanges.diff_against` won't detect changes in inherited models (`inherit=True`).

Problem resides at the way `_model_to_dict` serializes fields.

~~~ python
def _model_to_dict(model):
    return json.loads(serialize("json", [model]))[0]["fields"]
~~~
It uses `django.core.serializers.serialize`, but as explained [here](https://docs.djangoproject.com/en/2.2/topics/serialization/#inherited-models):

> if you have a model that uses multi-table inheritance, you also need to serialize all of the base classes for the model. This is because only the fields that are locally defined on the model will be serialized.

So it ignores any fields in the parent class.

**To Reproduce**
1. Have inherited models:

~~~ python
class Place(models.Model):
    name = models.CharField(max_length=50)

class Restaurant(Place):
    serves_hot_dogs = models.BooleanField(default=False)
~~~

Then from a `Restaurant` instance change an attribute from the parent class `Place.name`

~~~ python
r = Restaurant.objects.create(name="McDonalds")
r.name = "BurgerKing"
r.save()
~~~

Now try to detect changes:

~~~ python
new_record, old_record = r.history.all()
delta = new_record.diff_against(old_record)
for change in delta.changes:
    print("{} changed from {} to {}".format(change.field, change.old, change.new))
~~~

But it won't detect the `name` field so it doesn't detect any changes and `delta.changes=[]`

**Environment (please complete the following information):**
 - OS: Ubuntu 18.10
 - Django Simple History Version: 2.7.2
 - Django Version: 2.2.2

**Comment by hankchuan** [comment]
found same issue
