### ISSUE TITLE
history_user_id_field not supported with Django 1.11

### ISSUE THREAD

**Issue by altostratous** [treyhunner/django-simple-history#583]
**Describe the bug**
The prior version in the Django ORM has caused a failure while forming cached property names when processing the history model. 

**To Reproduce**
Steps to reproduce the behaviour:
1. In an already set up project with one model with history, configure `history_user_id_field`,
2. Make migrations,
3. Migrate,
4. Try to create one object of the aforesaid model,
5. Some exception occurs in the ORM while getting model fields in the model object descriptor.

**Expected behaviour**
The object should be created and the according history would be saved accordingly.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser (if applicable): postman
 - Django Simple History Version: 2.7.3
 - Django Version: 1.11.23
 - Database Version: PostgreSQL 10.5.0
 - Python: 3.6.8

**Additional context**
I tracked the stack and saw that the way to get property fields in Django ORM fails and it is changed in newer versions of Django.

So I think it is better to remove Django 1.11 from 2.7.3 support.

**Comment by rossmechanic** [comment]
Hi @altostratous thanks for this! What's the error you saw? MaybeI can help debug. The `history_user_is_field` was added a few months ago – if it's an easy fix, I'm happy to merge it. We won't drop support from Django 1.11 and python 2.7 until Django itself drops support for these versions in April 2020

**Comment by altostratous** [comment]
I could reproduce it with Python 3.5 and Django 1.11. However upgrading to the latest 1.11 i.e. 1.11.23 fixed this issue. It is related to Djagno issue [#28269](https://code.djangoproject.com/ticket/28269). So it is off this project and I'm closing this.
