### ISSUE TITLE
History Diffing - Display the __str__ value instead of the id for foreign key fields

### ISSUE THREAD

**Issue by aceaceace30** [treyhunner/django-simple-history#587]
I used history diffing on my project but it was displaying id for the foreign key fields.

Is there a Django way to do this? Should I query first from the model to get the field I needed?

**Comment by rossmechanic** [comment]
The historical foreign key fields store the id of the related field as opposed to being explicit foreign keys. This is on purpose, as the historical models are really supposed to be a log. Closing this
