### ISSUE TITLE
Read the Docs Django version support 2.2 missing

### ISSUE THREAD

**Issue by daniel-butler** [treyhunner/django-simple-history#595]
**Describe the bug**
On the readthedocs website the index.html page does not have the updated 2.2 version displayed.

**To Reproduce**
1. Go to [https://django-simple-history.readthedocs.io/en/latest/index.html](https://django-simple-history.readthedocs.io/en/latest/index.html)
2. Look at the supported versions table

**Expected behavior**
To match the docs/index.html page

**Screenshots**
![missing versions](https://user-images.githubusercontent.com/22578954/66524861-a1768e80-eac1-11e9-87b1-881e9ebfc0a2.PNG)

**Comment by guilleijo** [comment]
@daniel-butler Are you going to work on this or can I take it?

**Comment by sillycube** [comment]
New function bulk_update() in django 2.2 is not written in read the docs. So I guess django 2.2 is not fully supported yet though you may be able to run it.

**Comment by daniel-butler** [comment]
We should probably remove the django version support from the readme then

**Comment by rossmechanic** [comment]
Django 2.2 is fully supported in 2.7.3. Just an oversight that it didn't make it into the most recent stable release. It's on latest now, and will be updated this week for stable (releasing 2.8.0 which will include django 3.0 support)
