### ISSUE TITLE
'Options' object has no attribute 'simple_history_manager_attribute'

### ISSUE THREAD

**Issue by rifuso** [treyhunner/django-simple-history#600]
I tried to integrate the admin as instructed here:

https://django-simple-history.readthedocs.io/en/latest/admin.html

But I get this error (Django 2.2.6, Python 3.7):

File "/Users/f/virt_env/veeo-2VJsLjIm/lib/python3.7/site-packages/simple_history/admin.py" in history_view
  51.         history = getattr(model, model._meta.simple_history_manager_attribute)

Exception Type: AttributeError at /admin/website/sitepage/1/history/
Exception Value: 'Options' object has no attribute 'simple_history_manager_attribute'

Any suggestions?

**Comment by lyn716** [comment]
Maybe you have not add `HistoricalRecords` field on your model class like 
```python
from django.db import models
from simple_history.models import HistoricalRecords

class MyModel(models.Model):
    ...
    history = HistoricalRecords()
```

**Comment by rifuso** [comment]
I _do_ have it but on a parent, abstract class. Would that make a difference?

**Comment by melvinkcx** [comment]
I have the same problem, I have it in the parent class as well, you need to add the attribute into the subclasses as well.

**Comment by lyn716** [comment]
> I _do_ have it but on a parent, abstract class. Would that make a difference?

My configuration of abstract class is like:
```python
class ABCModel(models.Model):
    history = HistoricalRecords(inherit=True)

    class Meta:
        abstract = True
```

**Comment by melvinkcx** [comment]
I didn't scrutinize the code, but a quick and dirty fix for me was not to include `history` in parent but in the child classes.

**Comment by melvinkcx** [comment]
The docs to @lyn716's answer: https://django-simple-history.readthedocs.io/en/latest/historical_model.html#allow-tracking-to-be-inherited

**Comment by rossmechanic** [comment]
Looks like this has been resolved. Thanks @melvinkcx
