### ISSUE TITLE
Ability to disable admin Revert functionality

### ISSUE THREAD

**Issue by lazybird** [treyhunner/django-simple-history#602]
**Problem Statement**
I'm using django-simple-history in a project where we don't want to allow the "Revert" functionality in the admin.

**Describe the solution you'd like**
In `simple_history.admin.SimpleHistoryAdmin` we could have a way to disable the "revert" button.

    class PollHistoryAdmin(SimpleHistoryAdmin):
        enable_revert = False

**Comment by rossmechanic** [comment]
Actually working on that feature right now. Hoping to have it released soon (as a setting)

**Comment by gustavovaliati** [comment]
Hello @rossmechanic, congratz on this great project.

Question: do you still plan to add this feature?

**Comment by rossmechanic** [comment]
Yep @gustavovaliati - just pretty swamped with work at the moment so not sure when I'll get to it

**Comment by erikvw** [comment]
@rossmechanic @gustavovaliati -- maybe I can help. My PR #632 uses settings attribute only. Following that I have a PR that will control access to "revert" using admin permissions. I first would like the SETTINGS attribute PR (#632) merged and then move to controlling with permissions. @gustavovaliati, would controlling via permissions (which is admin functionality) meet your needs? Maybe you have comments for PR #632. Much appreciated.

**Comment by gustavovaliati** [comment]
Hey @erikvw ,
A global setting would be enough for me.
I will take a look to #632 ASAP;
Thanks!

**Comment by rossmechanic** [comment]
Fixed in #632
