### ISSUE TITLE
Model.validate_unique incompatible with django-simple-history

### ISSUE THREAD

**Issue by guyjeangilles** [treyhunner/django-simple-history#618]
**Describe the bug**
Including `self.validate_unique()` in an overridden `save()` method raises a `Validation Error` when reverting a model.
```
>>> model.history.earliest().instance.save()
...
django.core.exceptions.ValidationError: {'id': ['<model name> with this ID already exists.']}
```
Querying history doesn't raise an error, however. Directly using the model's `save()` function does not error either

```
>>> model.history.all()
# no errors raised
>>> model.save()
>>> model.save()
# no errors raised
```

**To Reproduce**
The following when added to any model throws an error. Save function is based off the [Django Docs](https://docs.djangoproject.com/en/2.2/ref/models/instances/#customizing-model-loading)
```
# models.py
...
def save(self, *args, **kwargs):
    """Error causing save"""
    self.validate_unique()
    super().save(*args, **kwargs)
...
```
The following does not raise an error
```
# models.py
...
def save(self, *args, **kwargs):
    """Properly functioning save"""
    super().save(*args, **kwargs)
...
```

**Expected behavior**
`book.history.earliest().instance.save()` should work whenever `model.save()` works.

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Django Simple History Version: 2.8.0
 - Django Version: 2.2.9
 - Database Version: (PostgreSQL) 12.1 (Debian 12.1-1.pgdg100+1)

**Additional context**
My environment is in a Docker container, but I can reproduce the error outside of Docker with a Django project made within a virtualenv environment
- Docker version: Docker version 19.03.5, build 633a0ea838
- Docker Compose Version: docker-compose version 1.24.1, build 4667896b

The exact traceback from my project
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/src/bookroost/catalog/models/records.py", line 102, in save
    self.validate_unique()
  File "/root/.local/lib/python3.8/site-packages/django/db/models/base.py", line 987, in validate_unique
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'id': ['Book with this ID already exists.']}
```

This is blocking me on my current project so any workaround would be greatly appreciated :)

EDIT: added tracebook

**Comment by rossmechanic** [comment]
@guyjeangilles what would you expect this to do? Validate unique checks to see if the id already exists in the database. If you're reverting a model (thus, really just updating the row that has the same id), it'll obviously validate the unique constraint. If you're trying to validate uniqueness on other fields, you could just call `self.validate_unique(exclude=["id"])`.  Other thing you could do is set the instance's `_state.adding=False` .

**Comment by guyjeangilles** [comment]
I should commented that I changed my implementation. You are correct.

**Comment by Myzel394** [comment]
@guyjeangilles Could you share your implementation? I'm addressing the same issue and I would like to just update the model on the given state.

**Comment by guyjeangilles** [comment]
@Myzel394 I ultimately ended up using [django-reversions](https://django-reversion.readthedocs.io/en/stable/)
