### ISSUE TITLE
How to prevent a requested change from being recorded?

### ISSUE THREAD

**Issue by abersheeran** [treyhunner/django-simple-history#619]
My project has two users, one is employees and the other is users. I just want to record the operation history of employees, not the records of users. 

How should I do? I didn't find a way to do it in the documentation.

**Comment by rossmechanic** [comment]
Just save without a historical record if the user is the user you don't want history for: 
https://django-simple-history.readthedocs.io/en/latest/querying_history.html#save-without-a-historical-record
