### ISSUE TITLE
Is it possible to show the changed field/fields on the Change history table?

### ISSUE THREAD

**Issue by sharozmirza** [treyhunner/django-simple-history#621]
If I change model object through the django admin site and if I do not use django-simple-history, I can see which field is changed in the `Action` column. Is it possible to achieve this using django-simple-history?

**Comment by sharozmirza** [comment]
I found a way to solve this issue. I added a ModelAdmin method and used History Diffing to add a custom field in the Change history table.

```
history_list_display = ['changed_fields']

def changed_fields(self, obj):
    if obj.prev_record:
        delta = obj.diff_against(obj.prev_record)
        return delta.changed_fields
    return None
```

**Comment by cpina** [comment]
Thanks for this snippet.

I wanted to do the same and that's my testing code at the moment:

```
    history_list_display = ['history_field_changes']

    def history_field_changes(self, obj):
        description_changes = ''

        if obj.prev_record:
            delta = obj.diff_against(obj.prev_record)

            for field in delta.changed_fields:
                old_value = escape(getattr(delta.old_record, field))
                new_value = escape(getattr(delta.new_record, field))
                description_changes += f'Field: {field} Prev: {old_value} Current: {new_value}<br>'

        return mark_safe(description_changes)
```

I don't need ellipsis for my case but it might be better. Still testing this but I thought of sharing.

(BTW, django-simple-history is really nicely done!)
