### ISSUE TITLE
FileField should be transformed into a CharField instead of a TextField

### ISSUE THREAD

**Issue by jcushman** [treyhunner/django-simple-history#623]
**Describe the bug**
`FileField` is turned into a `TextField` on history tables by the [`transform_field` function](https://github.com/treyhunner/django-simple-history/blob/68211b5dcbf79dfab71144fe1a524598b3656e23/simple_history/models.py#L546), but it should be turned into a CharField instead:

```
    elif isinstance(field, models.FileField):
        # Don't copy file, just path.
        field.__class__ = models.TextField  # should be CharField
```

Using `TextField` changes the representation of the file field in the database, because `FileField`s use the same database representation as `CharField`, not `TextField`.

For example, see Django's [postgres backend](https://github.com/django/django/blob/master/django/db/backends/postgresql/base.py#L72), where FileField is mapped to `'varchar(%(max_length)s)'` instead of `'text'`; the same is true for other backends. 

The upshot is that `FileFields` end up as `varchar`s in the primary table but as `text`s in the history table. This probably works fine for most users, since it's a more permissive field, but it's breaking a third party tool I'm using that expects the primary table and history table columns to have the same type.

**To Reproduce**
1. Create a history-tracked table with a `FileField`
2. Run `./manage.py sqlmigrate` to observe that the file field on the primary table is `varchar` but the field on the history table is `text`.

**Expected behavior**
Fields on the primary and history table should have the same type.

**Comment by rossmechanic** [comment]
Thanks for this. Not sure why it was a TextField in the first place, should be fine as a CharField. If you want to put up a backward compatible pr, I'd be happy to merge. The change should occur here https://github.com/treyhunner/django-simple-history/blame/57507748205a5dd2340893940c624749f1ba503d/simple_history/models.py#L546

and you'll want to have a setting that by default leaves them as TextFields, but allows you to switch them to CharFields
