### ISSUE TITLE
rate limit history of models?

### ISSUE THREAD

**Issue by CSchank** [treyhunner/django-simple-history#626]
**Problem Statement**
Perhaps I just haven't seen this as an option, but there doesn't appear to be a built-in way to change the frequency of how often new history is kept.

**Describe the solution you'd like**
For example, if a project has an auto-save where the client is saving every 5 seconds, we don't necessarily want to keep a history of every single change every 5 seconds. Instead, if the user is editing many times per minute, I'd like to be able to only save a new historical entry every, say one or two minutes. Thus, the model would still be saved, but we'd only end up with a maximum of one new history entry per minute.

**Describe alternatives you've considered**
Using the example shown of how to save the model without creating a history entry, we could manually check in our view whether there has been a save in the past minute and call that alternative, "history-free" save function instead. It seems like this could be more elegantly handled by the plugin itself, by simply providing a value.

**Comment by rossmechanic** [comment]
Haven't seen a lot of push for this use case. Feels like something you could throw in the `pre_create_historical_record` signal. Don't think it's worth adding to the core library, so going to close this issue.
