### ISSUE TITLE
Load ContentType model using django_apps instead of direct import

### ISSUE THREAD

**Issue by erikvw** [treyhunner/django-simple-history#629]
**Problem Statement**
I extend the `SimpleHistoryAdmin` class and depending on the loading sequence run into `AppRegistryNotReady` exception with the ContentType model class imported at the top of `SimpleHistoryAdmin`.

**Describe the solution you'd like**
Use django_apps to import the model and access it within `SimpleHistoryAdmin ` using an instance method, e.g. `content_type_model_cls()`

**Comment by rossmechanic** [comment]
merged #630. Thanks for raising this and fixing it
