### ISSUE TITLE
Add possibility to specify a default user for bulk_create_with_history

### ISSUE THREAD

**Issue by bmampaey** [treyhunner/django-simple-history#635]
**Problem Statement**
When calling bulk_create_with_history, if there is no _hystory_user set on the object, then no user will be associated with the change.

**Describe the solution you'd like**
Allow to specify a default_user to be set for history_user if _history_user is not set.

**Describe alternatives you've considered**
Setting the value of _history_user explicitly on each objects to create.

**Comment by rossmechanic** [comment]
Fixed in #653
