### ISSUE TITLE
It Recorded without changing fields

### ISSUE THREAD

**Issue by AliYmn** [treyhunner/django-simple-history#638]
**Describe the bug**
When i save without changing field, django-simple-history recorded this action. So i have too more stack logs. Also i used excluded_fields but there was no solution.

** Screen Shot **

<img src="https://serving.photos.photobox.com/391270082b965a06cb8ae9d2cd542afd39d414eba043497e12cd7dd2905da4d87891b378.jpg"/>

So, i have to solved this problem?

**Comment by rossmechanic** [comment]
This is expected behavior. DSH creates a new record every time `save` is called since it's a naive implementation.

**Comment by AliYmn** [comment]
@rossmechanic this is should be optional because my database increase about 100mb Within 1 month. Could  you offer a solution method?

**Comment by rossmechanic** [comment]
There's an option to save with creating a historical record: https://django-simple-history.readthedocs.io/en/latest/querying_history.html#save-without-a-historical-record

And there's a utility function to delete duplicate records: https://django-simple-history.readthedocs.io/en/latest/utils.html#clean-duplicate-history

That's the best I have for you. Not planning on solving this anytime soon.
