### ISSUE TITLE
Update the doc, please

### ISSUE THREAD

**Issue by JudiPuak** [treyhunner/django-simple-history#645]
**Problem Statement**
A.
I added history = HistoricalRecords() to my Location model
I also added admin.site.register(Location, SimpleHistoryAdmin) in admin.py
After migrating, I couldn't find the historicallocation table in admin as the doc says I would
However, when I clicked on the location table, clicked on an entry, now there is this History button on the upper corner

B.
I'd like to add a field in my location list html template:  when was the last time this location instance was modified
{{ location.history.history_date }} does not work even though the doc says that history table has history_date field in it
i spent a frustrating 30 minutes reading the doc over and over again but i could not find anything about this
I scoured stackoverflow too but with no success
after a cold bath, i found out that this works:  {{ location.history.first.history_date }}
i had to add ".first" in there
maybe i am not smart enough to understand the doc

**Describe the solution you'd like**
For A:  please investigate this.  If I am right, please update the doc.  If I am wrong, please advise me why i can't see the historicallocation table in admin
For B:  if indeed the doc does not have anything on this and if my solution is correct, please update the doc for future reference

all in all, django-simple-history works great.
i tried django-audit-log but it didn't work
thank you for your great work

**Comment by rossmechanic** [comment]
A. The doc doesn't say you would find a `HistoricalAllocation` table in admin. In creates the table in your database and is accessible through the `History` button on `Allocation`.
B. You can't access the history date by doing `location.history.history_date`. `history` is a manager on the base model. So you could do `location.history.latest("history_date").history_date` and pass that to the context.
