### ISSUE TITLE
How to display additional field in historical admin form?

### ISSUE THREAD

**Issue by decomorreno** [treyhunner/django-simple-history#659]
I added custom field to historical model (I was following this example https://django-simple-history.readthedocs.io/en/latest/historical_model.html#adding-additional-fields-to-historical-models) and it's working perfectly. Now I'm looking if there is some way to display this field in django admin form (I can display it in history_list_display, but it's a long TextField, so it's not very convenient). I read all the docs and searched existing issues and didn't find any similar problem. 

Thank you
Hubert

**Comment by Abhishek0057** [comment]
when you register a site in admin, similar to list_display=[], use this
history_list_display = ["address", 'address_type',"name"]

**Comment by dzsodzso63** [comment]
Why was this issue closed? The question is still relevant and was not answered
