### ISSUE TITLE
_change_reason on model instance does not set history_change_reason on save

### ISSUE THREAD

**Issue by ryancausey** [treyhunner/django-simple-history#660]
**Describe the bug**
The [documentation](https://django-simple-history.readthedocs.io/en/latest/historical_model.html#change-reason) states that `_change_reason` can be set on an instance before saving it to set what `history_change_reason` is. In practice this does not appear to work.

**To Reproduce**
1. Create a model similar to:
```
from django.db import models
from simple_history.models import HistoricalRecords

# Create your models here.

class TestModel(models.Model):
    foo = models.CharField(max_length=10)
    history = HistoricalRecords()

```
2. Save the model instance with `_change_reason` set and observe there is no history_change_reason.
```
In [1]: from testing.models import TestModel
In [2]: test_1 = TestModel(foo="test1")
In [3]: test_1.full_clean()
In [4]: test_1._change_reason = "this is a test"
In [5]: test_1.save()
In [6]: test_1.history.first().history_change_reason
In [7]: test_1.history.all()
Out[7]: <QuerySet [<HistoricalTestModel: TestModel object (1) as of 2020-05-04 19:08:35.846212+00:00>]>
```
3. Use `update_change_reason` to set the reason and observe it is set.
```
In [10]: from simple_history.utils import update_change_reason
In [11]: update_change_reason(test_1, "this is an update test")
In [12]: test_1.history.first().history_change_reason
Out[12]: 'this is an update test'
```

**Expected behavior**
When `_change_reason` is set on the model instance before save, the `history_change_reason` gets set on the historical model as described in the documentation.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Django Simple History Version: 2.8.0
 - Django Version: 2.2.11
 - Database Version: MySQL 5.7

**Comment by rossmechanic** [comment]
@ryancausey you're looking at the most recent version of the docs. This was updated in version 2.10.0. Prior to version `2.10.0`, you can use `changeReason` to add a change reason to a historical model. However, that method has been deprecated in favor of `_change_reason`, and `changeReason` will be removed in version `3.0`

**Comment by ryancausey** [comment]
doh!
