### ISSUE TITLE
Is there a script to import old admin history?

### ISSUE THREAD

**Issue by cbene06** [treyhunner/django-simple-history#661]
Hi all,

I successfully integrated django-simple-history in my app, thanks for this useful lib.

I would like to import my old admin history into the simple history database. Is there already a script for this, or should I create it from scratch?

Thanks,
Christophe

**Comment by rossmechanic** [comment]
Only script that exists sets the current state of your models as the beginning of history. No way to import your admin history though

**Comment by cbene06** [comment]
> 
> 
> Only script that exists sets the current state of your models as the beginning of history. No way to import your admin history though

Thanks
