### ISSUE TITLE
changed_by field with through model(that already has User ForeignKey)

### ISSUE THREAD

**Issue by csarcom** [treyhunner/django-simple-history#86]
This is what I have:
https://gist.github.com/csarcom/9938033

Problem:
```python
Exception: <class 'apps.user.models.CustomUserAccount'> has more than 1 ForeignKey to <class 'apps.user.models.CustomUser'>
```
My model should be ok with two foreign key to the same model using related_name right? But, since it is a through model, i guess django does not support it[1].
  
Any idea how can I save history_user on that model?

[1] https://code.djangoproject.com/ticket/8618

**Comment by macro1** [comment]
Since 1.6.0 history_user no longer defaults to having a reverse relationship (https://github.com/treyhunner/django-simple-history/pull/163), to avoid collisions like this.

Closing, should not be an issue anymore.
