### ISSUE TITLE
Compatibility with fixtures and initial data

### ISSUE THREAD

**Issue by BeccaMG** [treyhunner/django-simple-history#93]
django-simple-history DOES NOT record the creation of model instances when adding them on fixtures (by syncdb). The object is created (you can see it from django admin but "history" shows no record of it.

To read more about fixtures: https://docs.djangoproject.com/en/dev/howto/initial-data/

**Comment by macro1** [comment]
Closing... I believe #153 is a related issue. We should probably add some documentation about migration and fixture cases.
